### ISSUE TITLE
Calculate Response Error

### ISSUE THREAD

**Issue by Eliasmgprado** [gtkfi/ArcSDM#101]
I'm getting this error when executing Calculate Response (i'm using the demo data for orogenic gold).

![image](https://user-images.githubusercontent.com/34711222/42037562-160ba330-7abf-11e8-9a0c-240f14f80872.png)

My model:

![image](https://user-images.githubusercontent.com/34711222/42037600-31e0a484-7abf-11e8-94af-301bb3e389cc.png)

Running on Arcgis Pro 2.1.3

**Comment by Eliasmgprado** [comment]
I think the problem is that the output raster of the fucntion arcpy.MakeRasterLayer_management() has no attribute table.

**Comment by tachyon-work** [comment]
Have a look at the top of your first attached image. There is a message that says "This tool does not work properly on ArcGIS Pro".

It has an attribute table, but there are differences in the fundamental structure of attribute tables between desktop and Pro. This has not yet been resolved for SDM in Pro.

**Comment by Eliasmgprado** [comment]
Thanks for the help!
