### ISSUE TITLE
 getMaskSize Error

### ISSUE THREAD

**Issue by eliparsel** [gtkfi/ArcSDM#102]
I am trying to import the toolbox.pyt and create a stand alone script and I am facing some problems. I am running the following script based on the example Test_Calculate_weights.py : 
```
import arcpy
import os.path

# Create test db
gdbdir = r"C:/Users/arcgisadmin/Desktop/Test/"
gdb = "arcsdmtest.gdb"


# TODO: Adjust datadirs to point to demo data when it comes ready
datadir = r"C:/Users/arcgisadmin/Desktop/Test/demo/"

print ("Checking if database exists...")
if (not (os.path.exists(gdbdir + gdb))):
    print (" it doesn't, creating it...")
    arcpy.CreateFileGDB_management(gdbdir, gdb)
    print ("done.")

arcpy.CheckOutExtension("spatial")
arcpy.ImportToolbox("C:/shared/Upload/ElisavetUpload/Agrinio_WoE/ArcSDM/Toolbox/ArcSDM.pyt")
print ("Testing Calculate_weights -tool (Wofe)...")

# This _SHOULD_ work against filegeodatabase
arcpy.env.workspace = gdbdir + gdb
arcpy.env.scratchWorkspace = gdbdir + gdb

arcpy.env.outputCoordinateSystem = arcpy.SpatialReference("C:/shared/Upload/ElisavetUpload/WGS_1984_UTM_zone_34N.prj")

arcpy.env.cellSize = "25"

arcpy.env.mask = r"C:/shared/Upload/ElisavetUpload/Agrinio_WoE/Input_data/AOI.shp"
arcpy.Delete_management("C:/Users/arcgisadmin/Desktop/Test/demo/results/CalculateWeights.dbf")


aspect = r"C:\Users\arcgisadmin\Desktop\Test\demo\Aspect_.tif"
shapefile = r"C:\Users\arcgisadmin\Desktop\Test\demo\datasetsLS_merge_training.shp"
result = r"C:\Users\arcgisadmin\Desktop\Test\demo\results\CalculateWeights.dbf"

arcpy.ArcSDM.CalculateWeightsTool(aspect, "", shapefile, "Ascending", result, 2, 1, -99)
print ("Test complete.")

```
and i get the following error:

ERROR:   File "C:\shared\Upload\ElisavetUpload\Agrinio_WoE\ArcSDM\Toolbox\arcsdm\sdmvalues.py", line 92, in getMaskSize
    count = count * conversion;

ERROR:   File "C:\shared\Upload\ElisavetUpload\Agrinio_WoE\ArcSDM\Toolbox\arcsdm\sdmvalues.py", line 167, in appendSDMValues
    gp.addMessage( "%-20s %s" %( "Mask size:", str(getMaskSize(mapUnits))  ));
local variable 'count' referenced before assignment
GPMEs: 0 
ERROR: CW - PYTHON ERRORS:
Traceback Info:
  File "C:\shared\Upload\ElisavetUpload\Agrinio_WoE\ArcSDM\Toolbox\arcsdm\calculateweights.py", line 215, in Calculate
    arcsdm.sdmvalues.appendSDMValues(gp,  Unitarea, TrainingSites)

Error Info:
    <function format_exc at 0x00784FB0>

ERROR: Unhandled exception caught
Traceback (most recent call last):
  File "C:\shared\Upload\ElisavetUpload\Agrinio_WoE\ArcSDM\Toolbox\arcsdm\common.py", line 45, in execute_tool
    func(self, parameters, messages)
  File "C:\shared\Upload\ElisavetUpload\Agrinio_WoE\ArcSDM\Toolbox\arcsdm\calculateweights.py", line 215, in Calculate
    arcsdm.sdmvalues.appendSDMValues(gp,  Unitarea, TrainingSites)
  File "C:\shared\Upload\ElisavetUpload\Agrinio_WoE\ArcSDM\Toolbox\arcsdm\sdmvalues.py", line 167, in appendSDMValues
    gp.addMessage( "%-20s %s" %( "Mask size:", str(getMaskSize(mapUnits))  ));
  File "C:\shared\Upload\ElisavetUpload\Agrinio_WoE\ArcSDM\Toolbox\arcsdm\sdmvalues.py", line 92, in getMaskSize
    count = count * conversion;
UnboundLocalError: local variable 'count' referenced before assignment

Any idea what could be wrong?

**Comment by eliparsel** [comment]
OK, I found the error. For the mask I inserted the .tif instead of the .shp and I commented out at the sdmvalues.py  lines 91 , 92 when it raises an error if the mask is a Raster.

**Comment by tachyon-work** [comment]
People need to stop doing this. 

The mask has to be a raster to get accurate calculations from the tools. _This is not a negotiable parameter._ All the tools are fundamentally reliant on raster calculations. If your mask isn't a raster, all the raster calculations are wrong.

**Comment by trotor** [comment]
And I think you were using older version of sdmvalues that doesn't count the size correctly. I will also add warning about not using raster mask.

**Comment by artolaiho** [comment]
sdmvalues.py is fixed. Load the newest version of ArcSDM (V5.02) and test again. If the problem persists, reopen this issue.
