### ISSUE TITLE
Rescale raster values - cannot define output file

### ISSUE THREAD

**Issue by yeomo** [gtkfi/ArcSDM#104]
Unable to change the directory and output file for the Rescale Raster tool. Running in ArcGIS 10.5.1 on Windows 10 machine.

Have tried multiple ways to load the input file and different parameters selected but the automatically generated file path (to a geodatabase) cannot be edited prior to clicking OK to run the tool. This creates a bogus file format ".tif_rescaled" causing the tool to not complete.

Any help much appreciated

```
Start Time: Fri Jul 13 13:16:56 2018
Running script rescaleraster...

========== Rescale raster ==========
Starting rescale raster
   Negatives will be spread to new raster Min: -1.5706584
   Rescaling array[-1.5706584 - 1.570637] -> array[0 .. 1] 
   max(raster_array):3.1412954 diff:1
Calculation done.
Saving new raster...
   Output rastername: \\isad.isadroot.ex.ac.uk\UOE\User\ArcGIS\Default.gdb\clip_tanKUratio.tif_rescaled

Traceback (most recent call last):
  File "<string>", line 133, in execute
  File "F:\ArcSDM\Toolbox\arcsdm\rescale_raster.py", line 119, in execute
    myRasterBlock.save(output_rastername);
RuntimeError: ERROR 999998: Unexpected Error.

Failed to execute (rescaleraster).
Failed at Fri Jul 13 13:17:46 2018 (Elapsed Time: 50.03 seconds)
```

**Comment by Eliasmgprado** [comment]
You can edit this on enviroment > workspaces

**Comment by yeomo** [comment]
@Eliasmgprado thanks for your input, I cannot override this by changing the environment. I have altered both the current and the scratch workspace but no change. The tool will constantly revert to the path for the default geodatabase - I have tried to change this too but also same problem.

**Comment by yeomo** [comment]
By running ArcMap 10.5.1 in Administrator mode I generate a new error that means the tool does not run at at all. This appears to pertain to the main problem of generating a unique file name. Can anyone diagnose if this is this an error in the ArcSDM code or in my base Python set up?

`Traceback (most recent call last): File "", line 122, in updateParameters File "c:\program files (x86)\arcgis\desktop10.5\arcpy\arcpy\__init__.py", line 1414, in CreateUniqueName return gp.createUniqueName(base_name, workspace) File "c:\program files (x86)\arcgis\desktop10.5\arcpy\arcpy\geoprocessing\_base.py", line 411, in createUniqueName self._gp.CreateUniqueName(*gp_fixargs(args, True))) RuntimeError: ERROR 000110: \\isad.isadroot.ex.ac.uk\UOE\User\ArcGIS\Default.gdb does not exist`

**Comment by trotor** [comment]
By just looking at the path and "Administrator mode" I would start
examining the problem  by checking if you have read/write permissions to \\
isad.isadroot.ex.ac.uk\UOE\User\ArcGIS\   path as Administrator?

It seems to be environment I don't have any experience on - our user
environments lie on each computer, not on network drives. Will see this
ASAP.

**Comment by trotor** [comment]
Now that I look at the code, I think there is either
mistakes/misunderstandings in documentation or bug in ArcGis:
There is function called     def updateParameters(self, parameters): in
python toolboxes.

Documentation at
http://pro.arcgis.com/en/pro-app/arcpy/geoprocessing_and_python/customizing-tool-behavior-in-a-python-toolbox.htm
states that "altered" property of parameter should identify if user has
touched the parameter or not (so multiple firing of the updateparameters
updating output file name shouldn't be a problem). But it does so perhaps
it doesn't reset after validate like I expected.

I added test if user has touched the output file name parameter and now it
doesn't fire even once updating the name the first time you start the tool.
Anyhow, new version is now in the Github.

**Comment by yeomo** [comment]
Confirmed now working. Many thanks!
