### ISSUE TITLE
Run CalculateWeights on CentOS

### ISSUE THREAD

**Issue by eliparsel** [gtkfi/ArcSDM#105]
Hi,

I am trying to run the arcsdm tool on CentOS. Therefore I have installed the ArcGIS server 10.3 on CentOS 6.7  and I am importing the toolbox arcpy.ImportToolbox("ArcSDM.pyt"), which works fine, because when I check which Toolboxes are available I can see ArcSDM. 

But when I call:  
   arcpy.ArcSDM.CalculateWeightsTool(names_in, "", datasetsLS_merge_training, "Categorical", names_out, Confidence_Level_of_Studentized_Contrast, Unit_area__km_2_, -99, Success)

I get the following error:
"""Define the tool (tool name is the name of the class).""" AttributeError: Object: Tool or environment <CalculateWeightsTool_ArcSDM> not found.

Do you know how I could make it work? Is it compatible with CentOS?

Best,
Elisavet

**Comment by trotor** [comment]
Closing this.
