### ISSUE TITLE
In logistic regression Error 999999, Error exectuing founction.  Failed to execute (join field)

### ISSUE THREAD

**Issue by mianluqman** [gtkfi/ArcSDM#108]
![4](https://user-images.githubusercontent.com/6541275/46453929-89956c00-c7d6-11e8-9012-3bdeaf96ae03.png)

**Comment by trotor** [comment]
Thank you for your report! What inputs did you use and are you using latest
version? I think I saw these errors most when calculate weights was not
working correctly.

**Comment by mianluqman** [comment]
Yes. Weights are calculated for two parameters (i.e. 
![5](https://user-images.githubusercontent.com/6541275/46460165-bc972a00-c7ed-11e8-9217-447361dd02ff.png)
Road distance, stream distance). i use the latest ARCSDM version with ArGIS 10.5. 
Training  data set layer name was lengthy so it was not calculating the weights. It was problem with length of layer name. but weights are calculated now. its problem with logistic and Wofe response having errors. what to put in red i have tried different but not working. might be this is creating problem

**Comment by trotor** [comment]
Could you please paste full output from the output here? I think I haven't got example for free inputs and need to study it a bit more.

**Comment by mianluqman** [comment]
**ArcSDM 10 with ArcGIS 10.5 . Calculating response this error occurred**

Executing: CalculateResponse Road_Distance.tif;Total_Curvature.tif;Slope.tif;Profile_Curvature.tif;Plan_Curvature.tif;NDVI.tif;Geology.tif;Aspect.tif;Fault_Distance.tif;Stream_Distance.tif Road_Distance;Total_Curvature;Slope;Profile_Curvature;Plan_Curvature;NDVI;Geology;Aspect;Fault_Distance;Stream_Distance 2017_70_t true -99 0.00015625 E:\Workplace\Workspace_Centeroid\W_pprb E:\Workplace\Workspace_Centeroid\W_Std E:\Workplace\Workspace_Centeroid\W_MDvar E:\Workplace\Workspace_Centeroid\W_Tstd E:\Workplace\Workspace_Centeroid\W_Conf
Start Time: Thu Oct 11 20:13:22 2018
Running script CalculateResponse...

=========================================
=========================================
Workspace: E:\Workplace\Workspace_Centeroid
Scratch workspace: E:\Scratch
Prior Probability: 0.000082
Training Set: E:\Workplace\Workspace_toe\2017_70_t.shp
Number of Training Sites: 1183
Study Area Raster: E:\Workplace\DEM_Area_intg
Study Area Area (sq km): 2249.80198182
Unit Cell Area (sq km): 0.00015625
Map Units: meter
GP ERRORS:
ERROR 999998: Unexpected Error.
Failed to execute (Lookup).


PYTHON ERRORS:
Traceback Info:
  File "E:\Workplace\SDMArcGIS10\SDM\Scripts\NewCalcResp3.py", line 133, in <module>
    gp.Lookup_sa(Temp_Raster,"WEIGHT",Output_Raster)

Error Info:
    <class 'arcgisscripting.ExecuteError'>: ERROR 999998: Unexpected Error.
Failed to execute (Lookup).


Failed script CalculateResponse...

Traceback (most recent call last):
  File "E:\Workplace\SDMArcGIS10\SDM\Scripts\NewCalcResp3.py", line 133, in <module>
    gp.Lookup_sa(Temp_Raster,"WEIGHT",Output_Raster)
ExecuteError: ERROR 999998: Unexpected Error.
Failed to execute (Lookup).


Failed to execute (CalculateResponse).
Failed at Thu Oct 11 20:13:57 2018 (Elapsed Time: 34.71 seconds)

**Comment by trotor** [comment]
Okay, are you running latest version of ArcSDM? Newer versions should have
different kind of output in the begnining.

PLease check and download if necessary.

**Comment by artolaiho** [comment]
Can you test Logistic Regression again using modified tool on arto-dev branch.

**Comment by artolaiho** [comment]
Download whole ArcSDM from arto-dev branch and try again. There are many fixes as described on readme.  If the problem persists, reopen this issue and describe problem.
