### ISSUE TITLE
Calculate Weights tool still not working with filesystem workspace

### ISSUE THREAD

**Issue by DarthSysmon** [gtkfi/ArcSDM#11]
Downloaded and tested the 5.00.5 version. Still getting the same issue: The CW tool creates its own name for the output file in \Temp\ called "[filename]_CalculateWeightsT.dbf". If an attempt is made at changing the directory and file name, it reverts to "%WORKSPACE%\[filename]_WD": [http://i.imgur.com/CbZgWJx.png](url).

If the tool is run straight up as shown, an error still occurs: (http://i.imgur.com/tcUDO8b.png) suggesting that the file "%WORKSPACE%\[filename]_WC" already exists. However, the file doesn't seem to exist anywhere - I'm not sure where it was written to. It seems to not be where Environments is pointing.

**Comment by DarthSysmon** [comment]
Fixed one part of the issue: Removed the underscore in the paths to the working directories. The CW tool still won't allow you to change path or name (it ends up being _WC for categorical, _WD for descending tests).
Have to rename the tables after running them, and move them to correct folders. Seems the output is okay, except that a column called FID_ has been added that wasn't added by the old versions of ArcSDM. I will check some CW tables against old versions tomorrow, to see if output compares.

**Comment by trotor** [comment]
OKay, so you want to be able to disable autorenamer and you have some
errors working with directories containing underscores? I will take another
look at it.

For the naming of the files we got specs from our scientific advisors and
we thought it was good thing to autoname them with correct ending.

FID Field is always added for Shape/DBF output - I don't know why but I
expect they always are required to have identifier field (like in
geodatabase output it is OBJECTID).

**Comment by DarthSysmon** [comment]
The autorenamer is fine, although the name suggested is "[rastername]_CalculateWeightsT1.dbf" when the Evidence Raster Layer is at first dropped into the tool window. When clicking the folder icon to change the save location and returning to the tool window, save location changes to %WORKSPACE% and name to "[rastername]_WD for Cumulative Descending tests, for example.

The specs you got from your science advisors on the naming is different from what it used to be, and from what the tooltip still says for the Calculate Weights tool: It used to be _CA for cumulative ascending, _CD for cumulative descending, _CT for categorical, and _U for ungeneralised (unique) weights. Changing them to _WA, _WD etc. is fine if the Calculate Response tool is also updated to work with these endings, and the tooltips will need updating as well. I personally would prefer to stick with the old suffixes, so I don't have to rename hundreds of files when I rerun old models.

Somehow the old tool is able to not include FID_ in the output, see the attached zip of dbf/xml output from this new version and the old version of the SDM toolbox. The workspaces are set up similarly otherwise, and I'm happy to see that the outputs are identical.

[ArcSDM_CWTest.zip](https://github.com/gtkfi/ArcSDM/files/775283/ArcSDM_CWTest.zip)

**Comment by trotor** [comment]
Hi and thanks for the details, I will take a new look on the UI and name
the outputs as they were. This is clearly my mistake somewhere.

I will also take a look at the FID thing but it could be new ArcMap thing
(or something adding duplicate field).


T

**Comment by trotor** [comment]
Calculate weights endings fixed and 08 submitted to github. Please check if some errors still exist - I can't replicate missing data bug in this and need to check for alternative input data.

**Comment by trotor** [comment]
MOst likely UI error and now is fixed - User can change the output path.
