### ISSUE TITLE
ArcSDM 10 with ArcGIS 10.5. While calculating response this error occurred

### ISSUE THREAD

**Issue by mianluqman** [gtkfi/ArcSDM#111]
Executing: CalculateResponse Road_Distance.tif;Total_Curvature.tif;Slope.tif;Profile_Curvature.tif;Plan_Curvature.tif;NDVI.tif;Geology.tif;Aspect.tif;Fault_Distance.tif;Stream_Distance.tif Road_Distance;Total_Curvature;Slope;Profile_Curvature;Plan_Curvature;NDVI;Geology;Aspect;Fault_Distance;Stream_Distance 2017_70_t true -99 0.00015625 E:\Workplace\Workspace_Centeroid\W_pprb E:\Workplace\Workspace_Centeroid\W_Std E:\Workplace\Workspace_Centeroid\W_MDvar E:\Workplace\Workspace_Centeroid\W_Tstd E:\Workplace\Workspace_Centeroid\W_Conf
Start Time: Thu Oct 11 20:13:22 2018
Running script CalculateResponse...

=========================================
=========================================
Workspace: E:\Workplace\Workspace_Centeroid
Scratch workspace: E:\Scratch
Prior Probability: 0.000082
Training Set: E:\Workplace\Workspace_toe\2017_70_t.shp
Number of Training Sites: 1183
Study Area Raster: E:\Workplace\DEM_Area_intg
Study Area Area (sq km): 2249.80198182
Unit Cell Area (sq km): 0.00015625
Map Units: meter
GP ERRORS:
ERROR 999998: Unexpected Error.
Failed to execute (Lookup).

PYTHON ERRORS:
Traceback Info:
  File "E:\Workplace\SDMArcGIS10\SDM\Scripts\NewCalcResp3.py", line 133, in <module>
    gp.Lookup_sa(Temp_Raster,"WEIGHT",Output_Raster)

Error Info:
    <class 'arcgisscripting.ExecuteError'>: ERROR 999998: Unexpected Error.
Failed to execute (Lookup).

Failed script CalculateResponse...

Traceback (most recent call last):
  File "E:\Workplace\SDMArcGIS10\SDM\Scripts\NewCalcResp3.py", line 133, in <module>
    gp.Lookup_sa(Temp_Raster,"WEIGHT",Output_Raster)
ExecuteError: ERROR 999998: Unexpected Error.
Failed to execute (Lookup).

Failed to execute (CalculateResponse).
Failed at Thu Oct 11 20:13:57 2018 (Elapsed Time: 34.71 seconds)

**Comment by mianluqman** [comment]
**ArcSDM 10 with ArcGIS 10.5. While calculating response for 3 factors (Distance to fault,road and stream) calculated successfully. But for others not working...**

Executing: CalculateResponse Road_Distance.tif;Fault_Distance.tif;Stream_Distance.tif Road_Distance;Fault_Distance;Stream_Distance 2017_70_t true -99 0.00015625 E:\Workplace\Workspace_Centeroid\W_pprb E:\Workplace\Workspace_Centeroid\W_Std E:\Workplace\Workspace_Centeroid\W_MDvar E:\Workplace\Workspace_Centeroid\W_Tstd E:\Workplace\Workspace_Centeroid\W_Conf
Start Time: Thu Oct 11 20:35:29 2018
Running script CalculateResponse...

=========================================
=========================================
Workspace: E:\Workplace\Workspace_Centeroid
Scratch workspace: E:\Scratch
Prior Probability: 0.000082
Training Set: E:\Workplace\Workspace_toe\2017_70_t.shp
Number of Training Sites: 1183
Study Area Raster: E:\Workplace\DEM_Area_intg
Study Area Area (sq km): 2249.80198182
Unit Cell Area (sq km): 0.00015625
Map Units: meter
Creating Post Probability Raster...
=========================================
InExpression 1 ====> E:\Workplace\Workspace_Centeroid\W_pprb = EXP(-9.40675972523 + SUM(E:\Scratch\Road_Dist_W7,E:\Scratch\Fault_Dis_W3,E:\Scratch\Stream_Di_W3)) / (1.0 + EXP(-9.40675972523 + SUM(E:\Scratch\Road_Dist_W7,E:\Scratch\Fault_Dis_W3,E:\Scratch\Stream_Di_W3)))
Executing: MultiOutputMapAlgebra "E:\Workplace\Workspace_Centeroid\W_pprb = EXP(-9.40675972523 + SUM(E:\Scratch\Road_Dist_W7,E:\Scratch\Fault_Dis_W3,E:\Scratch\Stream_Di_W3)) / (1.0 + EXP(-9.40675972523 + SUM(E:\Scratch\Road_Dist_W7,E:\Scratch\Fault_Dis_W3,E:\Scratch\Stream_Di_W3)))"
Start Time: Thu Oct 11 20:36:35 2018
Succeeded at Thu Oct 11 20:36:44 2018 (Elapsed Time: 8.79 seconds)

Creating STD rasters...
=========================================
E:\Scratch\Road_Dist_S1
E:\Scratch\Fault_Dis_S2
E:\Scratch\Stream_Di_S2

Creating Post Probability STD Raster...
=========================================
InExpression 2 ====> E:\Workplace\Workspace_Centeroid\W_Std = SQRT(SQR(E:\Workplace\Workspace_Centeroid\W_pprb) * (0.000845308537616 + SUM(SQR(E:\Scratch\Road_Dist_S1),SQR(E:\Scratch\Fault_Dis_S2),SQR(E:\Scratch\Stream_Di_S2))))
Executing: MultiOutputMapAlgebra "E:\Workplace\Workspace_Centeroid\W_Std = SQRT(SQR(E:\Workplace\Workspace_Centeroid\W_pprb) * (0.000845308537616 + SUM(SQR(E:\Scratch\Road_Dist_S1),SQR(E:\Scratch\Fault_Dis_S2),SQR(E:\Scratch\Stream_Di_S2))))"
Start Time: Thu Oct 11 20:37:46 2018
Succeeded at Thu Oct 11 20:37:57 2018 (Elapsed Time: 11.01 seconds)
Missing Data Ignored. Missing Data Variance not calculated.
Calculating Confidence...
=========================================
InExpression 4====> E:\Workplace\Workspace_Centeroid\W_Conf = E:\Workplace\Workspace_Centeroid\w_pprb / E:\Workplace\Workspace_Centeroid\w_std
Executing: MultiOutputMapAlgebra "E:\Workplace\Workspace_Centeroid\W_Conf = E:\Workplace\Workspace_Centeroid\w_pprb / E:\Workplace\Workspace_Centeroid\w_std"
Start Time: Thu Oct 11 20:37:57 2018
Succeeded at Thu Oct 11 20:38:05 2018 (Elapsed Time: 8.31 seconds)
No Missing Data Variance.
Total STD same as Post Probability STD.
done
=========================================
Completed script CalculateResponse...
Succeeded at Thu Oct 11 20:38:06 2018 (Elapsed Time: 2 minutes 37 seconds)

**Comment by artolaiho** [comment]
Can you download whole ArcSDM from arto-dev branch and try again. There are many fixes as described on readme. If the problem persists, reopen this issue and describe problem.
