### ISSUE TITLE
Problem with NN tool.

### ISSUE THREAD

**Issue by smsm1920** [gtkfi/ArcSDM#112]
Hii to all, i was working on NN tool with arcsdm3.1 there i got a problem when i was executing the operation. I have formated all inputs as grid format and i used carlin demo files as inputs to test the operation and i have fixed the workspace but i got errors i am attaching files.
![error 1](https://user-images.githubusercontent.com/42085588/48360138-8ee2b200-e6c4-11e8-8fda-abc8017c5939.JPG)
![input environment](https://user-images.githubusercontent.com/42085588/48360140-8ee2b200-e6c4-11e8-9a36-71d612b01343.JPG)
![workspace definition](https://user-images.githubusercontent.com/42085588/48360141-8f7b4880-e6c4-11e8-951b-937537fea8df.JPG)

**Comment by artolaiho** [comment]
Load the newest version of ArcSDM (V5.02) and test again. If the problem persists, reopen this issue.
