### ISSUE TITLE
NEED for online training(payed) IN Spatial data modeler tool SDM 

### ISSUE THREAD

**Issue by smsm1920** [gtkfi/ArcSDM#116]
Hi to all,
Wish you all a very good time. I am a senior research fellow from a prestigious Indian geophysical institute 
IIT(ISM) DHANBAD. I am currently working in mineral exploration and for that i need a good training from experts if any one from here is interested to make this possible please let me know.
I am talking about a payed training for it (not free).
mail id -subhendu.agp@gmail.com

**Comment by tachyon-work** [comment]
I don't run it online, face to face only. In my experience it's the only way you will get anything out of it. 

If you're in India, try contacting Alok Porwal at IIT Mumbai. Alok is a former colleague of mine from when he was based overseas, he's got experience with the previous versions of SDM, has previously worked in mineral exploration projects, and it may be more viable for you to travel to visit him in person to get some help with your workflows.
