### ISSUE TITLE
Non-technical question

### ISSUE THREAD

**Issue by tachyon-work** [gtkfi/ArcSDM#120]
How do you think we should we be citing the updated version of this software in manuscripts? Has GTK come up with a reference we can use?

**Comment by VesaNy** [comment]
We do not have a proper publication yet but we are working on it. Hopefully later this year there is a reference. Until then you should perhaps only refer to the GITHUB site. Sorry for the inconvenience.

**Comment by tachyon-work** [comment]
Thanks. Not a real issue, just something I was thinking about while writing!
