### ISSUE TITLE
ROC  tool fail

### ISSUE THREAD

**Issue by letter1225** [gtkfi/ArcSDM#121]
When I tried to calculate ROC curve and AUC value with ARCSDM on ARCMAP10.2, it reported "fail to execute ROC tool", as shown in the following. 

**Traceback (most recent call last):
  File "<string>", line 735, in execute
  File "E:\ARCSDM\arcsdm\roctool.py", line 56, in execute
    if not SpatialReferencesAreEqual(positives_sref, raster_sref, messages):
  File "E:\ARCSDM\arcsdm\roctool.py", line 376, in SpatialReferencesAreEqual
    if sref1.latitudeOfOrigin != sref2.latitudeOfOrigin:
AttributeError: SpatialReference: Get attribute latitudeOfOrigin does not exist

Failed to execute (ROCTool).
Failed at Tue Jun 18 11:38:33 2019 (Elapsed Time: 0.20 seconds)**

![image](https://user-images.githubusercontent.com/29188553/59653310-0c732100-91c4-11e9-85e5-e3fec4f619d4.png)

**Comment by letter1225** [comment]
What's the probable reason and how can I fix it?

**Comment by trotor** [comment]
It is quite possible that it doesn't work on 10.2. Do you have possibility
to upgrade to newer version?

**Comment by letter1225** [comment]
I have also tried on 10.3 and 10.5, then encountered with the license issue, as I have described in the other issue. But it worked well on 10.2 when I deleted the line of code checking the latitude of origin.

**Comment by trotor** [comment]
Ok, I will forward this message to Kimmo about the necessity of that check.

**Comment by artolaiho** [comment]
Load the newest version of ArcSDM (V5.02) and test again. If the problem persists, reopen this issue.
