### ISSUE TITLE
ArcSDM for latest version of ArcMap (10.6.1) and ArcGIS Pro (2.3.3)

### ISSUE THREAD

**Issue by KhaledMAli** [gtkfi/ArcSDM#122]
Hi There, 

I am using ArcSDM version 5.01.07. 

**With ArcMap 10.6.1:** 
Under Weights of Evidence tools, I was able to use _Calculate Weights, Calculate Response_ and _Logistic regression_ tools. The README document states that it partially works with 10.6. I haven't tried all the tools but it would be great if you could let me know which tools do and do not work. 

**With ArcGIS Pro 2.3.3:** 
I was able to use Calculate Weights but the _Calculate Response_ and _Logistic Regression_ failed. Although the README file says that it should work with _Pro version 2+_, its not working for me. In fact the error message says that "_This tool does not work properly on ArcGIS Pro_". 

Is there a plan to make these tools work in the latest versions of both ArcMap and ArcGIS Pro?

Thanks. 

![Capture](https://user-images.githubusercontent.com/52176181/60046233-d4bd1b00-9694-11e9-8197-0a571b4b057e.PNG)

**Comment by trotor** [comment]
Hi, the text when running the tool is right and documentation is wrong: It
doesn't work correctly on ArcGis pro at the moment. Unfortunately I don't
have schedule for the planned updates. I wish I had more time for this
project but I don't and we need to ask Vesa or someone else to manage and
prioritize time.

**Comment by KhaledMAli** [comment]
Thanks for your reply. I'm glad that it does work with the latest version of ArcMap although I haven't tested all the tools yet. 

I'll get in touch with Vesa to discuss the updates.

**Comment by artolaiho** [comment]
Hello. Can you download whole ArcSDM from arto-dev branch and try again. There are many fixes as described on readme.

**Comment by artolaiho** [comment]
Load the newest version of ArcSDM (V5.02) and test again. If the problem persists, reopen this issue.
