### ISSUE TITLE
ROC tool Failed to execute

### ISSUE THREAD

**Issue by susimachado** [gtkfi/ArcSDM#125]
![image](https://user-images.githubusercontent.com/39741101/68528294-8de06280-02cf-11ea-9619-6cbc97606a01.png)

I don't know where the problem is. Please help me.
Thanks.

**Comment by trotor** [comment]
hi, quick thing to try: Remove all blanks from your directory paths, seems
like describe function is failing.

**Comment by artolaiho** [comment]
Load the newest version of ArcSDM (V5.02) and test again. 
If the problem persists, reopen this issue.
