### ISSUE TITLE
How does roctool choose negative samples?

### ISSUE THREAD

**Issue by letter1225** [gtkfi/ArcSDM#127]
Thank you for the excellent ArcSDM toolbox, it really has helped me a lot. Now I have one question: how does the roctool determine negative samples in plotting a ROC curve if I only input the shapefile of positive points?   Thank you very much!

**Comment by kkorhone** [comment]
If the negatives are not provided, the tool chooses them randomly. The tool does this 10,000 times in order to detemine confidence intervals for the ROC curve and AUC value.

**Comment by letter1225** [comment]
Thank you very much. Does the tool randomly choose the same number of negative samples as positive samples each time?

**Comment by kkorhone** [comment]
Yes, exactly like that.

**Comment by artolaiho** [comment]
This issue is probably solved.
