### ISSUE TITLE
Calculate weights crashes in arcgis pro with filesystem workspace

### ISSUE THREAD

**Issue by trotor** [gtkfi/ArcSDM#130]

**Comment by trotor** [comment]
![image](https://user-images.githubusercontent.com/10844537/79325090-3c40a180-7f19-11ea-83e6-80ed98577b84.png)

**Comment by artolaiho** [comment]
ArcGIS Pro 2.5 cannot add CONTRAST field to dBase database on Python code calculateweights.py.
This python code works if CONTRAST field is not used. There is no problem on ArcGIS Desktop 10.6.1 with dBase or ArcGIS Pro with file geodatabase. I reported this to Esri.

**Comment by artolaiho** [comment]
I continued tests. Seems that if dBase field name is same as alias name (no case sensitive), for example: when field name is CONTRAST and alias name is Contrast, ArcGIS Pro 2.5 crashes. When I added underscore to end of alias name (Contrast_), Pro worked succesfully.

**Comment by artolaiho** [comment]
A corrected version can be found in the Arto-dev branch.
