### ISSUE TITLE
calculate response and "missing data"

### ISSUE THREAD

**Issue by VesaNy** [gtkfi/ArcSDM#14]
I have one layer with missing data (with pixel value of -99). Calclulate weights run well but something breaks when running calculate response. Here the messages:

Executing (Calculate response): CalculateResponse rcam4kres;rcaemres;rc_apv_hg4 C:\ArcSDM_New\Test_VMN\wofe2.gdb\rcam4kres_WA;C:\ArcSDM_New\Test_VMN\wofe2.gdb\rcaemres_WA;C:\ArcSDM_New\Test_VMN\wofe2.gdb\rc_apv_hg4_WD training_07_c # -99 0.5 C:\ArcSDM_New\Test_VMN\wofe2.gdb\W_pprb C:\ArcSDM_New\Test_VMN\wofe2.gdb\W_std C:\ArcSDM_New\Test_VMN\wofe2.gdb\W_MDvar C:\ArcSDM_New\Test_VMN\wofe2.gdb\W_Tstd C:\ArcSDM_New\Test_VMN\wofe2.gdb\W_conf
Start Time: Wed Feb 15 13:15:36 2017
Running script CalculateResponse...
Reloaded arcsdm modules

========== arcsdm values  ==========
                     ArcSdm 5.00.05 for ArcGis (Pro and Desktop)

Workspace:           C:\ArcSDM_New\Test_VMN\wofe2.gdb (LocalDatabase)
Scratch workspace:   C:\ArcSDM_New\Test_VMN\wofe2.gdb (LocalDatabase)
Mask:                "study_area2" and it is RasterLayer
Mask size:           18642.0375
Cell Size:           50.0
# Training Sites:    33
Unit Cell Area:      0.5km^2, Cells in area: 37284.075 
Prior Probability:   0.000885
Training Set:        C:\arcsdm\klappi\data\training_07_c.shp
Study Area Raster:   C:\arcsdm\klappi\data\study_area2
Study Area Area:     18642.0375km^2
Map Units:           meter

========================================= Starting calculate response =========================================
Study Area:          37284.075
# training points:   33
Prior_prob:          0.000885096384985
Input rasters: [u'rcam4kres', u'rcaemres', u'rc_apv_hg4']
Input rasters: [u'rcam4kres', u'rcaemres', u'rc_apv_hg4']

Creating weight rasters 
=========================================
Processing rcam4kres
 Temp_Raster=C:\ArcSDM_New\Test_VMN\wofe2.gdb\temp_raster54
 Wts_Table=C:\ArcSDM_New\Test_VMN\wofe2.gdb\rcam4kres_WA
 Output_Raster: C:\ArcSDM_New\Test_VMN\wofe2.gdb\rcam4kres_W4
 
Processing rcaemres
 Temp_Raster=C:\ArcSDM_New\Test_VMN\wofe2.gdb\temp_raster55
 Wts_Table=C:\ArcSDM_New\Test_VMN\wofe2.gdb\rcaemres_WA
 Output_Raster: C:\ArcSDM_New\Test_VMN\wofe2.gdb\rcaemres_W4
 
Processing rc_apv_hg4
 Temp_Raster=C:\ArcSDM_New\Test_VMN\wofe2.gdb\temp_raster56
 Wts_Table=C:\ArcSDM_New\Test_VMN\wofe2.gdb\rc_apv_hg4_WD
 Output_Raster: C:\ArcSDM_New\Test_VMN\wofe2.gdb\rc_apv_hg4_W3
 

Getting Post Logit raster...
=========================================
 Input_data_str: "C:\ArcSDM_New\Test_VMN\wofe2.gdb\rcam4kres_W4" + "C:\ArcSDM_New\Test_VMN\wofe2.gdb\rcaemres_W4" + "C:\ArcSDM_New\Test_VMN\wofe2.gdb\rc_apv_hg4_W3"
 InexpressionPlog: -7.02892852099 + ("C:\ArcSDM_New\Test_VMN\wofe2.gdb\rcam4kres_W4" + "C:\ArcSDM_New\Test_VMN\wofe2.gdb\rcaemres_W4" + "C:\ArcSDM_New\Test_VMN\wofe2.gdb\rc_apv_hg4_W3")

Creating Post Probability Raster...
=========================================
InExpression 1 ====> Exp(-7.02892852099 + ("C:\ArcSDM_New\Test_VMN\wofe2.gdb\rcam4kres_W4" + "C:\ArcSDM_New\Test_VMN\wofe2.gdb\rcaemres_W4" + "C:\ArcSDM_New\Test_VMN\wofe2.gdb\rc_apv_hg4_W3")) / (1.0 + Exp(-7.02892852099 + ("C:\ArcSDM_New\Test_VMN\wofe2.gdb\rcam4kres_W4" + "C:\ArcSDM_New\Test_VMN\wofe2.gdb\rcaemres_W4" + "C:\ArcSDM_New\Test_VMN\wofe2.gdb\rc_apv_hg4_W3")))
Postprob: C:\ArcSDM_New\Test_VMN\wofe2.gdb\W_pprb

Executing: RasterCalculator "Exp(-7.02892852099 + ("C:\ArcSDM_New\Test_VMN\wofe2.gdb\rcam4kres_W4" + "C:\ArcSDM_New\Test_VMN\wofe2.gdb\rcaemres_W4" + "C:\ArcSDM_New\Test_VMN\wofe2.gdb\rc_apv_hg4_W3")) / (1.0 + Exp(-7.02892852099 + ("C:\ArcSDM_New\Test_VMN\wofe2.gdb\rcam4kres_W4" + "C:\ArcSDM_New\Test_VMN\wofe2.gdb\rcaemres_W4" + "C:\ArcSDM_New\Test_VMN\wofe2.gdb\rc_apv_hg4_W3")))" C:\ArcSDM_New\Test_VMN\wofe2.gdb\W_pprb
Start Time: Wed Feb 15 13:16:14 2017
Exp(-7.02892852099 + (Raster(r"C:\ArcSDM_New\Test_VMN\wofe2.gdb\rcam4kres_W4") + Raster(r"C:\ArcSDM_New\Test_VMN\wofe2.gdb\rcaemres_W4") + Raster(r"C:\ArcSDM_New\Test_VMN\wofe2.gdb\rc_apv_hg4_W3"))) / (1.0 + Exp(-7.02892852099 + (Raster(r"C:\ArcSDM_New\Test_VMN\wofe2.gdb\rcam4kres_W4") + Raster(r"C:\ArcSDM_New\Test_VMN\wofe2.gdb\rcaemres_W4") + Raster(r"C:\ArcSDM_New\Test_VMN\wofe2.gdb\rc_apv_hg4_W3"))))
Succeeded at Wed Feb 15 13:16:20 2017 (Elapsed Time: 5,88 seconds)

Creating STD rasters...
=========================================
 Processing rcam4kres
OutputRaster:C:\ArcSDM_New\Test_VMN\wofe2.gdb\rcam4kres_S4 exists: 0
RasterLayer=OutRas_lyr2
Temp_Raster=C:\ArcSDM_New\Test_VMN\wofe2.gdb\temp_raster57
C:\ArcSDM_New\Test_VMN\wofe2.gdb\rcam4kres_S4
 Processing rcaemres
OutputRaster:C:\ArcSDM_New\Test_VMN\wofe2.gdb\rcaemres_S4 exists: 0
RasterLayer=OutRas_lyr2
Temp_Raster=C:\ArcSDM_New\Test_VMN\wofe2.gdb\temp_raster58
C:\ArcSDM_New\Test_VMN\wofe2.gdb\rcaemres_S4
 Processing rc_apv_hg4
OutputRaster:C:\ArcSDM_New\Test_VMN\wofe2.gdb\rc_apv_hg_S3 exists: 0
RasterLayer=OutRas_lyr2
Temp_Raster=C:\ArcSDM_New\Test_VMN\wofe2.gdb\temp_raster59
C:\ArcSDM_New\Test_VMN\wofe2.gdb\rc_apv_hg_S3

Creating Post Probability STD Raster...
=========================================
Sum_args: Square("C:\ArcSDM_New\Test_VMN\wofe2.gdb\rcam4kres_S4") + Square("C:\ArcSDM_New\Test_VMN\wofe2.gdb\rcaemres_S4") + Square("C:\ArcSDM_New\Test_VMN\wofe2.gdb\rc_apv_hg_S3")
=========================================
InExpression = SquareRoot(Square("C:\ArcSDM_New\Test_VMN\wofe2.gdb\W_pprb") * (0.030303030303 +(Square("C:\ArcSDM_New\Test_VMN\wofe2.gdb\rcam4kres_S4") + Square("C:\ArcSDM_New\Test_VMN\wofe2.gdb\rcaemres_S4") + Square("C:\ArcSDM_New\Test_VMN\wofe2.gdb\rc_apv_hg_S3"))))
InExpression 2 ====> SquareRoot(Square("C:\ArcSDM_New\Test_VMN\wofe2.gdb\W_pprb") * (0.030303030303 +(Square("C:\ArcSDM_New\Test_VMN\wofe2.gdb\rcam4kres_S4") + Square("C:\ArcSDM_New\Test_VMN\wofe2.gdb\rcaemres_S4") + Square("C:\ArcSDM_New\Test_VMN\wofe2.gdb\rc_apv_hg_S3"))))

Executing: RasterCalculator SquareRoot(Square("C:\ArcSDM_New\Test_VMN\wofe2.gdb\W_pprb") * (0.030303030303 +(Square("C:\ArcSDM_New\Test_VMN\wofe2.gdb\rcam4kres_S4") + Square("C:\ArcSDM_New\Test_VMN\wofe2.gdb\rcaemres_S4") + Square("C:\ArcSDM_New\Test_VMN\wofe2.gdb\rc_apv_hg_S3")))) C:\ArcSDM_New\Test_VMN\wofe2.gdb\W_std
Start Time: Wed Feb 15 13:16:58 2017
SquareRoot(Square(Raster(r"C:\ArcSDM_New\Test_VMN\wofe2.gdb\W_pprb")) * (0.030303030303 +(Square(Raster(r"C:\ArcSDM_New\Test_VMN\wofe2.gdb\rcam4kres_S4")) + Square(Raster(r"C:\ArcSDM_New\Test_VMN\wofe2.gdb\rcaemres_S4")) + Square(Raster(r"C:\ArcSDM_New\Test_VMN\wofe2.gdb\rc_apv_hg_S3")))))
Succeeded at Wed Feb 15 13:17:03 2017 (Elapsed Time: 5,04 seconds)
**GP ERRORS:

PYTHON ERRORS:
Traceback Info:
  File "C:\ArcSDM_New\Toolbox\arcsdm\calculateresponse.py", line 400, in Execute
    import MissingDataVar_Func

Error Info:
    <type 'exceptions.ImportError'>: No module named MissingDataVar_Func

Unhandled exception caught
Traceback (most recent call last):
  File "C:\ArcSDM_New\Toolbox\arcsdm\common.py", line 45, in execute_tool
    func(self, parameters, messages)
  File "C:\ArcSDM_New\Toolbox\arcsdm\calculateresponse.py", line 400, in Execute
    import MissingDataVar_Func
ImportError: No module named MissingDataVar_Func**

Completed script CalculateResponse...
Failed to execute (Calculate response).
Failed at Wed Feb 15 13:17:03 2017 (Elapsed Time: 1 minutes 27 seconds)

**Comment by trotor** [comment]
Thank you Vesa for your report, will take a look at this next.

T

**Comment by trotor** [comment]
Hi, this and the crash could be now fixed in 5.00.07 version. We are checking if the calculations come out correctly as this needed some workarounds for missing old functions.

i will respond the same in all related bug reports.

T

**Comment by trotor** [comment]
This crash fixed. Miscalculations exist
