### ISSUE TITLE
Failed to execute (ROCTool).

### ISSUE THREAD

**Issue by tabassum-irs** [gtkfi/ArcSDM#144]
I am using ArcGIS 10.8 in windows 11 and ArcSDM 5.0 version tool for Plotting AUC . But this error is showing . what is the solution of it????

Please help!!!!!!!!!!!!!!!!!!!!!

Executing: ROCTool GPS_point_field_survey # Reclass_Weig5 C:\Users\HP\Desktop
Start Time: Thu Aug 10 11:08:14 2023
Running script ROCTool...
Performing Monte Carlo simulation (10000 realizations).
Realization #1000 (AUC = 0.748)
Realization #2000 (AUC = 0.800)
Realization #3000 (AUC = 0.773)
Realization #4000 (AUC = 0.780)
Realization #5000 (AUC = 0.806)
Realization #6000 (AUC = 0.779)
Realization #7000 (AUC = 0.782)
Realization #8000 (AUC = 0.806)
Realization #9000 (AUC = 0.801)
Realization #10000 (AUC = 0.750)
Completed Monte Carlo simulation.
Reclass_Weig5: AUC = 0.771.
Reclass_Weig5: 95% confidence interval = 0.709-0.820.

Traceback (most recent call last):
  File "<string>", line 655, in execute
  File "F:\Thesis Data\ArcSDM-5.00.22\ArcSDM-5.00.22\Toolbox\arcsdm\roctool.py", line 89, in execute
    pylab.legend(plot_handles, legend_items, 4)
  File "C:\Python27\ArcGIS10.8\lib\site-packages\matplotlib\pyplot.py", line 3552, in legend
    ret = gca().legend(*args, **kwargs)
  File "C:\Python27\ArcGIS10.8\lib\site-packages\matplotlib\axes\_axes.py", line 548, in legend
    raise TypeError('Invalid arguments to legend.')
TypeError: Invalid arguments to legend.

Failed to execute (ROCTool).
Failed at Thu Aug 10 11:08:27 2023 (Elapsed Time: 13.38 seconds)

**Comment by lehtonenp** [comment]
Hello @tabassum-irs, and thank you for raising this issue. There is a pull request that fixes the error. There were `Invalid arguments to legend` just like in your error message.

**Comment by kkorhone** [comment]
This should now be fixed.
Problem: legend() cannot be called with three positional arguments
Solution: the call "legend(plot_handles, legend_items, 4)" is now replaced with the call "legend(plot_handles, legend_items, loc=4)"
