### ISSUE TITLE
Grid name length error using Calculate Response

### ISSUE THREAD

**Issue by DarthSysmon** [gtkfi/ArcSDM#15]
Hi there. I'm getting ERROR 00878 when running the Calculate Response tool with rasters with names of near-13 characters length: "ERROR 000878: Output raster: The length of the grid base name in [...]\faults1km13_W0 is longer than 13". Which is true, it is 14 characters. But the last 3 characters, _W0, is added by the script to a temporary file. The problem does not occur in the old version of the SDM, which also makes the _W0 temporary rasters.

Cheers,
S

**Comment by trotor** [comment]
Hi and thanks for the report. Will take a look at this right after
nodatavalidation bug. This one should be easy.

T

**Comment by trotor** [comment]
Confirmed issue with Grid max names - resolving back to max 13 char strings...

**Comment by trotor** [comment]
This fixed in .13
