### ISSUE TITLE
CalculateWeightsTool fails with Carlin demo data

### ISSUE THREAD

**Issue by VesaNy** [gtkfi/ArcSDM#17]
Here an error found by Gary. He is running the tools using ArcGIS 10.3 and using the Carlin data sets from the original ArcSDM package.

Vesa
I put my data in a personal geodatabase and ran calculate weights, which failed. The error message is below.

Executing: CalculateWeightsTool sbintgb # TrainGB Descending C:\SDM10.0\CarlinPGDB.mdb\sbint_WD 2 1 -99
Start Time: Thu Feb 16 16:33:22 2017
Running script CalculateWeightsTool...
Reloaded arcsdm modules

========== arcsdm values  ==========
                     ArcSdm 5.00.02 for ArcGis (Pro and Desktop)

Workspace:           C:\SDM10.0\CarlinPGDB.mdb
Scratch workspace:   C:\TEMP
Mask:                "stdyarea250" and it is RasterLayer
Mask size:           56799.0625
Cell Size:           250.0
# Training Sites:    32
Unit Cell Area:      1.0km^2, Cells in area: 56799.0625 
Prior Probability:   0.000563
Training Set:        C:\SDM10.0\CarlinPGDB.mdb\TrainGP
Study Area Raster:   C:\SDM10.0\CarlinPGDB.mdb\stdyarea250
Study Area Area:     56799.0625km^2
Map Units:           meter
========== Calculate weights ==========
Creating table:      %WORKSPACE%\sbint_WD (Descending)
ERROR 999999: Error executing function.
GPMEs: 0 
CW - PYTHON ERRORS:
Traceback Info:
  File "C:\ArcSDM-master\Toolbox\arcsdm\calculateweights.py", line 258, in Calculate
    wtsrow.Count = row.Count

Error Info:
    <function format_exc at 0x121B20B0>

Unexcpected exception caught
Traceback
  File "C:\ArcSDM-master\Toolbox\arcsdm\common.py", line 45, in execute_tool
    func(self, parameters, messages)

Error Info:
ERROR 999999: Error executing function.
ArcPy ERRORS:

Completed script CalculateWeightsTool...
Failed to execute (CalculateWeightsTool).
Failed at Thu Feb 16 16:33:38 2017 (Elapsed Time: 15.90 seconds)

Gary

**Comment by trotor** [comment]
This seems to be very hard to debug - related to Access database. Will delay fix!

Recommended workaround: Use either files or filegeodatabase!
