### ISSUE TITLE
Calculate weights tool

### ISSUE THREAD

**Issue by trotor** [gtkfi/ArcSDM#2]
Make CW tool work in ArcGis pro - initial convert.

**Comment by trotor** [comment]
Compiles and runned once - issues must be verified.

**Comment by DarthSysmon** [comment]
Hi there. I've been trying to run the CW tool in ArcGIS 10.2, but get an error. It seems it converts any input to 'Output weights table' to %WORKSPACE%\[filename]_WC and removes .dbf. Help? Cheers Simon

**Comment by trotor** [comment]
Hi, i think we still have some bugs on working with old style dbf and shp
inputs - it works with filegeodatabase workspaces. You need to wait for the
fix or is it possible for you to use filegeodatabase as %workspace%?

T

**Comment by trotor** [comment]
Hi again, to repicate the situation, could you please explain what types of
files are you using and what is your Workspace set to?

Thanks, Tero

**Comment by DarthSysmon** [comment]
Thanks for your help, Tero.

Workspace is set to E:\DATA\ArcSDM\TCIOCG_test\Working. We run a lot of models using ArcSDM and have standard procedures in place.

The grids are model grids from a WoE model we ran a couple of years ago. The binary grid is a generic 8-bit unsigned integer grid. The training data is a point-geometry shapefile. The grid used for mask and clipping is an 8-bit unsigned integer thematic grid.

Cheers,
Simon

**Comment by trotor** [comment]
Thanks for your help, I will setup similar test env today and try to
pinpoint problems.

**Comment by trotor** [comment]
Ok, "fixed". It still won't let you add ".dbf" to the table name. Instead
it will automaticvally add it when it detects you are working with
filesystem workspace.

New version is 5.00.04
