### ISSUE TITLE
 Calculate Weights still seems to be unable to handle missing data (-99)

### ISSUE THREAD

**Issue by trotor** [gtkfi/ArcSDM#20]
Calculate weights doesn't work with missing data.

**Comment by DarthSysmon** [comment]
Looks like the calculate weights tool forgets about no data (-99) for contrast calculation: The larger the proportion of NoData area is compared to Data areas, the smaller the discrepancy between calculated C for the old weightstables (_CT) and the new ones (_CC).

[NoData_rasters.xlsx](https://github.com/gtkfi/ArcSDM/files/788922/NoData_rasters.xlsx)

Cheers,
Simon

**Comment by DarthSysmon** [comment]
I tested this with a random raster, reclassified to -99, 1 and 2. Same problem between old and new toolbox: There is a difference is calculated W+, W-, C and StudC - and therefore Weight. S_ values and W_STD are similar though.

**Comment by trotor** [comment]
Could be fixed in 5.00.14. Calculate weights calculated total area wrong on No-data values
