### ISSUE TITLE
Calculate weights: automated naming of output tables

### ISSUE THREAD

**Issue by VesaNy** [gtkfi/ArcSDM#26]
Automated naming of output tables feature in calculate weights tool is causing problems with Arc GRID format with limit of 13 characters in grid names. We should perhaps either 
1) disable this feature totally, 
2) let the user edit the given name or 
3) truncate the name within 13 character limit.

Current workaround is using other grid formats that allow long names.

**Comment by VesaNy** [comment]
Sorry, I got confused. Calculate weights is creating a table, not a grid. There should be no limitations on the length of table names.

**Comment by trotor** [comment]
Naming fixed on toolbox - user can now input what ever name they wish. If they like to use automatic name, they must clear the field.
