### ISSUE TITLE
ROC tool crashes

### ISSUE THREAD

**Issue by trotor** [gtkfi/ArcSDM#35]
Executing: ROCTool OrogenicAu # GammaOGD C:\arcsdm\LapinKaiku\OrogenicAu_ROCTool1.dbf
Start Time: Wed May 24 09:56:59 2017
Running script ROCTool...

Traceback (most recent call last):
  File "<string>", line 267, in execute
  File "C:\ArcSDM_New\Toolbox\arcsdm\roctool.py", line 30, in execute
    _roc_curve, _roc_ints, _auc_value, _auc_confints = CalculateCurveForModel(messages, raster_descr, negatives_descr, positives_x, positives_y)
  File "C:\ArcSDM_New\Toolbox\arcsdm\roctool.py", line 94, in CalculateCurveForModel
    messages.addMessage("Performing Monte Carlo simulation (%d realizations)." % self.NUM_REALIZATIONS)
NameError: global name 'self' is not defined

Failed to execute (ROCTool).
Failed at Wed May 24 09:57:12 2017 (Elapsed Time: 13.26 seconds)

Ajamme molemmat tätä ArcGIS 10.4.1 versiolla.

**Comment by kkorhone** [comment]
Fixed

**Comment by trotor** [comment]
Closed and in on 5.00.16
