### ISSUE TITLE
Calculate response Demo crashes

### ISSUE THREAD

**Issue by trotor** [gtkfi/ArcSDM#44]
Steps:
1.	Download ArcSDM and ArcSDM_DemoData.
2.	Unzip ArcSDM-Master.zip, this creates ArcSDM-master folder.
3.	Unzip ArcSDM_DemoData.zip inside ArcSDM-master folder, this creates Data folder.
4.	Execute file InitWorkDir.bat inside ArcSDM-master, this creates work folder.
5.	Open ArcMAP 10.5 and open ArcSDM_Desktop_work.mxd inside work folder
6.	Create folder connection for ArcSDM-master folder.
7.	In Arc Toolbox, select add toolbox and select ArcSDM-master/Toolbox/ ArcSDM.pyt
8.	In CalculateResponse demo.tbx, Step 1 and Step 2 appear with a red x. As well as LogisticRegressionDemotbx

9.	In Step 1, select edit and appears the model where calculate weights appears with a red x.
10.	Selected Calculate weights directly with
a.	Evidence raster layer : lithoname200k, rc_dnsstru, rc_magn_res4k, rc_till_cu, rc_em_real
b.	Training points orogenic gold thin
c.	Changed Output to end in WD
d.	Everting else as default
11.	Run calculate response with the obtained tables, orogenic_gold_thin and defaults
12.	ArcMAP closes. Output obtained before crash:
```
Running script CalculateResponse...
Reloaded ArcSDM modules
========== arcsdm values  ==========
ArcSdm 5.00.12 for ArcGis (Pro and Desktop)
Workspace:           C:\Users\irca\Downloads\ArcSDM-master\work\database.gdb (LocalDatabase)
Scratch workspace:   C:\Users\irca\Downloads\ArcSDM-master\work\scratch.gdb (LocalDatabase)
Mask:                "study_area" and it is FeatureClass
Mask size:           98856.95500162625
Cell Size:           500.0
# Training Sites:    40
Unit Cell Area:      1.0km^2, Cells in area: 98856.95500162625
Prior Probability:   0.000405
Training Set:        C:\Users\irca\Downloads\ArcSDM-master\work\database.gdb\Study\orogenic_gold_thin
Study Area Raster:   C:\Users\irca\Downloads\ArcSDM-master\work\database.gdb\study_area
Study Area Area:     98856.95500162625km^2
Map Units:           meter
========================================= Starting calculate response =========================================
Study Area:          98856.95500162625
# training points:   40
Prior_prob:          0.00040462504635452285
Input rasters: ['lithoname200k', "'Reclassified rasters\\rc_dnsstru'", "'Reclassified rasters\\rc_em_real'", "'Reclassified rasters\\rc_magn_res4k'", "'Reclassified rasters\\rc_till_cu'"]
Input rasters: ['lithoname200k', 'rc_dnsstru', 'rc_em_real', 'rc_magn_res4k', 'rc_till_cu']
Creating weight rasters
=========================================
Processing lithoname200k
 


```

**Comment by trotor** [comment]
Could someone test this with new demo dataset?

T

**Comment by trotor** [comment]
Waiting for feedback, can't replicate

**Comment by trotor** [comment]
Can't replicate this with user description of the problem with new demodata and toolbox (10.4.1 arcgis).


```
Completed script CalculateResponse...   Succeeded at Wed Jul 19 10:07:13 2017 (Elapsed Time: 1 minutes 17 seconds) | Completed script CalculateResponse...   Succeeded at Wed Jul 19 10:07:13 2017 (Elapsed Time: 1 minutes 17 seconds) | Completed script CalculateResponse... |   | Succeeded at Wed Jul 19 10:07:13 2017 (Elapsed Time: 1 minutes 17 seconds)
-- | -- | -- | -- | --
Completed script CalculateResponse...   Succeeded at Wed Jul 19 10:07:13 2017 (Elapsed Time: 1 minutes 17 seconds) | Completed script CalculateResponse... |   | Succeeded at Wed Jul 19 10:07:13 2017 (Elapsed Time: 1 minutes 17 seconds)
Completed script CalculateResponse...
  | Succeeded at Wed Jul 19 10:07:13 2017 (Elapsed Time: 1 minutes 17 seconds)

```

**Comment by trotor** [comment]
Confirmed crash in ArcGis pro 2.0 investigating

**Comment by trotor** [comment]
Command line :  `arcpy.ImportToolbox(r"C:\arcsdm\toolbox\arcsdm.pyt")

arcpy.env.workspace = r"C:\ArcSDM\work\database.gdb"
arcpy.env.scratchWorkspace = r"C:\ArcSDM\work\database.gdb"
arcpy.env.mask = r"C:\ArcSDM\work\database.gdb\study_area"

arcpy.ArcSDM.CalculateResponse(r"C:\ArcSDM\work\database.gdb\lithoname200k", r"C:\ArcSDM\work\database.gdb\lithoname200k_WC", r"C:\ArcSDM\work\database.gdb\orogenic_gold_thin", None, -99, 1, r"C:\ArcSDM\work\database.gdb\W_pprb", r"C:\ArcSDM\work\database.gdb\W_std", r"C:\ArcSDM\work\database.gdb\W_MDvar", r"C:\ArcSDM\work\database.gdb\W_Tstd", r"C:\ArcSDM\work\database.gdb\W_conf")`

**Comment by trotor** [comment]
Crash happens on this line (186):
gp.AddJoin_management(RasterLayer,"Value",Wts_Table,"CLASS")

**Comment by irvcaza** [comment]
Managed to execute _Calculate response_ successfully using only 
- rc_till_cu
- rc_magn_res4k
- rc_em_real
But any combination that contains 
- **rc_dnsstru or** 
- **lithoname_200k** 
produces the error. Therefore is more related to the layers.

Studding deeper I found out that the Coordinate Systems differ
- orogenic_gold_thin -> EUREF_FIN_TM35FIN
- rc_dnsstru -> **ETRS_1989_Transverse_Mercator**
- rc_em_real -> EUREF_FIN_TM35FIN
- rc_till_cu -> EUREF_FIN_TM35FIN
- rc_magn_res4k -> EUREF_FIN_TM35FIN
- lithoname200k -> **ETRS_1989_Transverse_Mercator**

That is possibly the origin of our error

**Comment by trotor** [comment]
It is problem with output spatial reference - needs confirmation

**Comment by trotor** [comment]
https://www.dropbox.com/s/nxmzxex0jhpbskq/issue44.rar?dl=0

Waiting for confirmation of bug.

**Comment by irvcaza** [comment]
Issue sent to Esri DE, waiting for response.

**Comment by trotor** [comment]
Closing this - demodata fixed and problem pinpointed. Thanks!

**Comment by trotor** [comment]
Reopening this because of #98

**Comment by Eliasmgprado** [comment]
I'm with the same problem, using the data in ArcSDM_Demodata/DemoData_version_files (dowloaded from github) using the following layers for Wofe Demo testing:

* orogenic_Au
* rc_dnsstru
* rc_em_real
* rc_till_cu
* rc_magn_res4k
* lithoname200k 

ArcMap crashes when Calculate Response is executed. I have already checked the spatial reference and its ok.

**Comment by trotor** [comment]
Okay, thank you for your feedback! Which version of ArcGis are you running
this against?

**Comment by Eliasmgprado** [comment]
Running on ArcMap 10.5.1

**Comment by Eliasmgprado** [comment]
**I got it!** 

The problem is in line 211 of calculateresponse.py

`arcpy.AddJoin_management(RasterLayer,"VALUE",Wts_Table,"CLASS")`

When i run the code below
```
my_raster_layer = arcpy.Raster(RasterLayer)
if my_raster_layer.hasRAT:
     arcpy.AddMessage("Has a VAT!")
else:
     arcpy.AddMessage("No VAT!")
```

before the line 205  - arcpy.MakeRasterLayer_management(Input_Raster,RasterLayer) - 
the algorithm output "No VAT", that is, the RasterLayer created do not have Attribute Table, probably this is causing the crash.

This way, i have make the following modifications to the calculateresponse.py code for circunvent this issue.

- Comment line 205
`arcpy.MakeRasterLayer_management(Input_Raster,RasterLayer)`
- Modified line 211, replacing RasterLayer by Input_Raster
`arcpy.AddJoin_management(Input_Raster,"VALUE",Wts_Table,"CLASS")`
 - Modified line 236, replacing RasterLayer by Input_Raster
`arcpy.CopyRaster_management(Input_Raster,Temp_Raster,'#','#',NoDataArg2)`
- Comment line 381
`gp.makerasterlayer(Input_Raster,RasterLayer)`
- Comment line 383, No need for AddJoin again, as the Input_Raster already has the join
`gp.AddJoin_management(Input_Raster,"Value",Wts_Table,"CLASS")`
- Modified line 397, replacing RasterLayer by Input_Raster
`arcpy.CopyRaster_management(Input_Raster, Temp_Raster,"#","#",NoDataArg2)`

After these modifications the code is running well. However for AddJoin_management() function work with the Input_Raster, i have to export all the used rasters to a gdb before running the tool.

Thanks for the attention, and for the help.

**Comment by trotor** [comment]
Thanks for the work you have put on this, very good!  Does your comment in
the end mean that this doesn't work with file system inputs, just with
geodatabase? It is one serious showstopper for some tools (we would like
them to work on both environments)

**Comment by Eliasmgprado** [comment]
Yes, for AddJoin_management to work without use the makerasterlayer function, the input must be with geodatabase. But if you want the tool to accept file system inputs, you can add some lines of code to transform the input files to geodatabase before start join the tables.

**Comment by trotor** [comment]
Okay, when I have time I must study this. Perhaps there is way to make it
work on both with alternative data flows.

**Comment by artolaiho** [comment]
I haven't same test data than above but I have tested with current data. My experience is that Calculate Response (from arto-dev branch) works with ArcMap and ArcGIS Pro if workspace is either File Geodatabase (which I recommend) or File System.

Here is short test using python on ArcMap 10.6.1:
>>> import arcpy
>>> print (arcpy.env.mask)
C:\ArcSDM\Work\DemoData_version_files\derivatives\study_area_g\study_area_g
>>> import arcgisscripting
>>> gp = arcgisscripting.create()
>>> print(gp.workspace)
C:\ArcSDM\work
>>> print(gp.scratchworkspace)
C:\ArcSDM\work\Scratch
>>> Input_Raster = r"C:\ArcSDM\Work\DemoData_version_files\geology\lithoname200k\lithoname200k"
!!! Calculate Response may crash if Input Raster is RasterDataset but don't crash if it is RasterBand
>>> Wts_Table = r"C:\ArcSDM\Work\DemoData_version_files\lithoname200k_CT.dbf"
!!! This table is output from Calculate Weights.
>>> Training_Points = r"C:\ArcSDM\Work\DemoData_version_files\shape_files\Orogenic_Au.shp"
>>> outputrastername = Input_Raster.replace(".","_")
>>> outputrastername = outputrastername[:10] + "W"
>>> Output_Raster = gp.CreateScratchName(outputrastername, '', 'rst', gp.scratchworkspace)
>>> RasterLayer = "OutRas_lyr"
>>> arcpy.MakeRasterLayer_management(Input_Raster,RasterLayer)
<Result 'OutRas_lyr'>
!!! MakeRasterLayer writes RasterLayer to TEMP folder.
>>> arcpy.AddJoin_management(RasterLayer,"VALUE",Wts_Table,"CLASS")
<Result 'OutRas_lyr'>
>>> Temp_Raster = gp.CreateScratchName('tmp_rst', '', 'rst', gp.scratchworkspace)
>>> arcpy.CopyRaster_management(RasterLayer,Temp_Raster,'#','#','#')
<Result 'C:\\ArcSDM\\work\\Scratch\\tmp_rst17'>
>>> outras = arcpy.sa.Lookup(Temp_Raster,"WEIGHT")
>>> 
and so on... (without crash)

**Comment by artolaiho** [comment]
This works also with ArcMap 10.6.1 and ArcGIS Pro 2.5:
import arcpy
arcpy.ImportToolbox(r"C:\ArcSDM\Toolbox\ArcSDM.pyt")
arcpy.env.workspace = r"C:\ArcSDM\Work"
arcpy.env.scratchWorkspace = r"C:\ArcSDM\Work\Scratch"
arcpy.env.mask = r"C:\ArcSDM\Work\DemoData_version_files\derivatives\study_area_g\study_area_g"
!!! Note: Mask must be RasterBand, not RasterDataset (study_area_g twice above)
!!! Also Input raster must be RasterBand, not RasterDataset (lithoname200k twice below)
arcpy.ArcSDM.CalculateResponse(r"C:\ArcSDM\work\DemoData_version_files\geology\lithoname200k\lithoname200k", r"C:\ArcSDM\Work\DemoData_version_files\lithoname200k_CT.dbf", r"C:\ArcSDM\work\DemoData_version_files\shape_files\Orogenic_Au.shp", "#", -99, 1, r"C:\ArcSDM\work\W_pprb", r"C:\ArcSDM\work\W_std", r"C:\ArcSDM\work\W_MDvar", r"C:\ArcSDM\work\W_Tstd", r"C:\ArcSDM\work\W_conf")

**Comment by artolaiho** [comment]
Load the newest version of ArcSDM (V5.02) and test again. If the problem persists, reopen this issue.
