### ISSUE TITLE
NNinput files crash

### ISSUE THREAD

**Issue by VesaNy** [gtkfi/ArcSDM#55]
Following error when running the Neural Network Input Files script:

Executing (Neural network input files): NeuralNetworkInputFiles C:\MPM\TestNN\NN1 gold_deposits # ni_deposits # nn1 true C:\MPM\TestNN\BC_NN.txt C:\MPM\TestNN\nn1_train C:\MPM\TestNN\nn1_class
Start Time: Thu Sep 07 13:03:02 2017
Running script NeuralNetworkInputFiles...

Traceback (most recent call last):
  File "<string>", line 404, in execute
AttributeError: 'module' object has no attribute 'nninputfiles'

Failed to execute (Neural network input files).
Failed at Thu Sep 07 13:03:02 2017 (Elapsed Time: 0,08 seconds)

**Comment by trotor** [comment]
Fixed, waiting more input

**Comment by trotor** [comment]
Closing this - month without input, expected to work. Reopen if needed

**Comment by tachyon-work** [comment]
Just to follow up on this, I get the exact same error with the NN Output Files tool after successfully running geoXplore:
![image](https://user-images.githubusercontent.com/32659237/31471178-f9a824bc-af43-11e7-9431-3899faf2d3eb.png)
