### ISSUE TITLE
Issue with very small "IN" regions

### ISSUE THREAD

**Issue by DarthSysmon** [gtkfi/ArcSDM#57]
Hi there.

There seem to be a minimum "2" relative area size for testing binary rasters with Calculate Weights. I am testing the new toolbox' ability to deal with perfect correlation, and it works fine when buffering a training data set 1 km and setting inside buffer = 2, outside buffer = 1. The ratio of IN/OUT is about 0.0035 in that case.

However, reducing buffer size to 100 m (IN/OUT ratio 0.00004) results in WPLUS and WMINUS of 0 in both the CLASS 1 and 2 rows of the resulting weightstable. It also gives an error suggesting overlapping training data within the unit cell distance. At a prior probability of 0.000121, the IN/OUT ratio is actually less than the prior probability; can that be causing the issue?

![perfectcorrelation](https://user-images.githubusercontent.com/25653028/31260357-b35135e2-aaa9-11e7-9c0f-3633dd790d40.JPG)

**Comment by trotor** [comment]
This is something I better forward to our testers for review, thanks for the feedback!

**Comment by trotor** [comment]
Comment: Are there actually more than 1 training point per cell size? There should be only one per cell - and that is why we have the thinning selection tool (Quick comment derived from reply from Vesa Nykänen)

**Comment by tachyon-work** [comment]
Having the same problem. If the evidence layer is categorical, and the favourable class area/total area is smaller than the prior probability, you get the error message. 

In this example, favourable class area = 0.2275 km2, total area = 102198.97 km2, so ratio is 0.000002226 - an order of magnitude smaller than the prior probability. There is definitely not more than 1 training point per cell.
![image](https://user-images.githubusercontent.com/32659237/31472918-f502b0da-af4d-11e7-9c65-4ee1fbc8da3f.png)
