### ISSUE TITLE
Maximum number of predictive maps in Calculate Response?

### ISSUE THREAD

**Issue by DarthSysmon** [gtkfi/ArcSDM#61]
Hi there.

Running the new Calculate Response tool on an old model with 15 predictive maps kept resulting in the tool crashing with an ERROR 00530: Error running expression: rcexec(). Seems to be a RuntimeError 999998: Unexpected Error, failing to execute (RasterCalculator).

However, the crashes were never quite the same. Other times it was Failed to execute (Lookup), or list index out of range. And they were not with a specific evidence map. I ran combinations of those maps that failed, resulting in successful Calculate Response runs. And I ran the full model in different orders, resulting in crashes.

However, reducing the number of maps to 14 always resulted in a successful Calculate Response tool run. Is there a maximum of 14 maps to be used? We have run models with 18 or more evidence maps in the past, successfully at least from a script perspective.

Cheers,
Simon

**Comment by trotor** [comment]
I will try this and will forward this question to ESRI if it is the case. There is no known limit on development side.

**Comment by DarthSysmon** [comment]
Tried another model with 18 maps, getting the same error with the rcexec command when calculating the post prob raster, this time even with 10 maps. We also tried with a model in ArcMap 10.3.1, which seems to work. I am testing using 10.5 though.

**Comment by DarthSysmon** [comment]
Another update: Running this model with the existing weights tables caused crashes to desktop. So I re-ran the Calculate Weights tool for all maps before running Calculate Response. Might be a 10.5 issue.

**Comment by tachyon-work** [comment]
Worked with existing weights tables and rasters in 10.3.1. Same data. Had no issues with combining lots of maps.

**Comment by DarthSysmon** [comment]
Must be a 10.5 thing then.

**Comment by trotor** [comment]
Is this issue good to close and assume as 10.5 bug? I can't run 10.5 anywhere yet to confirm

**Comment by DarthSysmon** [comment]
Since the new toolbox is supposed to work with ArcGIS 10.5 and Pro, I don't think it is a good idea to simply close it. I'll try to reproduce the error with other rasters in another workspace. But this really needs to be tested thoroughly in current versions of ArcGIS too.

**Comment by trotor** [comment]
Okay. I will introduce new tag for the issues - "Highpriority" or "Showstopper" to prioritize between these. I am running out of my personally scheduled time

**Comment by DarthSysmon** [comment]
Prioritise it low, please, until I have consistently reproduced it in 10.5 Haven't had time to test it in Pro, as I haven't had the time to recreate 15 predictive maps in Pro yet. And Pro crashes straight away trying to use older version input maps.
So prioritise low, but don't close it.

Cheers,
S

**Comment by artolaiho** [comment]
Load the newest version of ArcSDM (V5.02) and test again. If the problem persists, reopen this issue.
