### ISSUE TITLE
Confidence on Contrast or StudC?

### ISSUE THREAD

**Issue by tachyon-work** [gtkfi/ArcSDM#62]
Set confidence to 0.5 and the following message comes up:
![image](https://user-images.githubusercontent.com/32659237/31365338-fbc71e5c-adc6-11e7-96e2-d986a73cbde6.png)

The message is indicating that the confidence is being defined by the contrast value when it should be on the StudC value. Is this a typo mistake in the warning message provided or a mistake in the code?

**Comment by trotor** [comment]
I will forward this to team experts - I don't understand the problem clearly enough

**Comment by VesaNy** [comment]
Confidence (i.e. studentized contrast) is calculated by dividing the contrast value by the contrast standard deviation value. So it is defined by them both. The warning should maybe say:  "**No Contrast for type Categorical satisfied the user defined confidence level** of studentized contrast". Maybe we could leave out "of studentized contrast" and it would be clear enough.

**Comment by tachyon-work** [comment]
Either works. The "user confidence contrast" is just confusing :)

**Comment by trotor** [comment]
Fixed this typo in 5.00.24
