### ISSUE TITLE
Calculate weights in batch mode

### ISSUE THREAD

**Issue by tachyon-work** [gtkfi/ArcSDM#63]
Running in ArcGIS 10.3.1:

Running Calculate Weights in batch mode doesn’t allow you to modify table names (works fine in previous SDM). Double click in relevant batch mode box to open to edit table name, make changes, click ok, and the box comes up empty. You’re stuck with the default. This only appears to be an issue in batch mode.

**Comment by tachyon-work** [comment]
Issue may be intermittent or caused by some input file issue (?). Reran and it's working now.

**Comment by trotor** [comment]
Leaving this open for a while.

**Comment by trotor** [comment]
CLosing - most likely file issue...
