### ISSUE TITLE
NN UC grid

### ISSUE THREAD

**Issue by tachyon-work** [gtkfi/ArcSDM#64]
Running ArcGIS 10.3.1:
In the input files tool, I get an error if the UC grid happens to be joined to another table already (apparent issue with FID). Had the UC grid joined to a targets polygon layer from a separate WofE analysis and the input files tool failed to complete until the join was removed. Does not necessarily need fixing, but can you please make a note of it in documentation so that users know to do this before running the tool.

**Comment by trotor** [comment]
I see if there is a way to detect already joined tables.

**Comment by trotor** [comment]
Unfortunately at this point there doesn't seem to be such easy way withoug try/catch.... Closing issue
