### ISSUE TITLE
Request: Reclassify that masks properly

### ISSUE THREAD

**Issue by tachyon-work** [gtkfi/ArcSDM#65]
A request rather than an issue as such...

The reclassify tool in Spatial Analyst fails to mask the output raster properly, and just outputs to the max x and y extents. Can a reclassify tool be incorporated to the SDM toolbox that actually does the reclassify properly which clips the output to the study area mask?

**Comment by trotor** [comment]
What do you mean by properly? Would you like it to actually cut the output to fit the exact shape?

**Comment by VesaNy** [comment]
The reclassify tool is using the environmental parameters like all the other geoprocessing tools in ArcGIS. So you need to define "mask" in Raster Analysis tab of Environments settings. This is a standard procedure and it works fine. The output is using the mask defined and clips to the mask perfectly.  So there is no need to recode this into SDM toolbox.

**Comment by tachyon-work** [comment]
It doesn't work. If you have an irregular shaped raster mask and you run the reclassify tool in Spatial Analyst, it does not clip it to the mask on output. It outputs garbage where there should be null cells in the irregular shape, so you have to run the extract by mask tool after the reclassify. This is an ArcGIS issue (at least in 10.1 through to 10.3.1), and probably doesn't exist in every version. Maybe 10.5 fixed it?

**Comment by VesaNy** [comment]
Here an example how it works in 10.4.1

![image](https://user-images.githubusercontent.com/25792453/31433471-22d84b18-ae82-11e7-99ba-3cd9f85e2d0d.png)

**Comment by tachyon-work** [comment]
Example from 10.3.1 (yes, I have checked the environment settings):
Run Euclidean Distance tool on a fault layer, it masks properly:
![image](https://user-images.githubusercontent.com/32659237/31460538-4e002fc6-af23-11e7-985a-0293a8a7db10.png)

Run the reclassify tool and it doesn't mask out the null area:
![image](https://user-images.githubusercontent.com/32659237/31460624-897e98c6-af23-11e7-8cdc-4144685a6674.png)

It's been an issue for years. Your example suggests that it may now be resolved. But it remains an issue from at least 10.1 to 10.3.1.

**Comment by trotor** [comment]
Assuming this is working in 10.4.1+ and closing issue
