### ISSUE TITLE
Grand WofE Error

### ISSUE THREAD

**Issue by tachyon-work** [gtkfi/ArcSDM#68]
Getting an error running Grand WofE. Claims there's a mismatch between number of input rasters and the input raster types. There's not - I have 10 input layers and 10 input raster types. How are you meant to input the raster types? Previous SDM had drop down field, but unclear as to how we are meant to separate the C's or O's in this version. I have tried using comma (,), semicolon (;) and a space. Same error each time.

![image](https://user-images.githubusercontent.com/32659237/31470451-4cbb159a-af41-11e7-9881-ce15730e2cee.png)

![image](https://user-images.githubusercontent.com/32659237/31470669-7578c95a-af41-11e7-989b-b9628f41832a.png)

**Comment by trotor** [comment]
You need to separate types by ; at this point. Multiple strings didn't work as they used to. Tell me how it goes with ;

**Comment by tachyon-work** [comment]
That worked, thanks. Followed by following error:
![image](https://user-images.githubusercontent.com/32659237/31516104-d1b84706-aff3-11e7-935b-1a75c482d185.png)

Appears to be a problem with it not producing the weights tables correctly?

**Comment by trotor** [comment]
Could be problem with non-database input files...

**Comment by tachyon-work** [comment]
I put everything in a gdb just to test this. Get the following:

> Executing: GrandWofe gwofe2 D:\testSDM\gwofe\testSDM.gdb\d2ag;D:\testSDM\gwofe\testSDM.gdb\d2as;D:\testSDM\gwofe\testSDM.gdb\d2au;D:\testSDM\gwofe\testSDM.gdb\d2bi;D:\testSDM\gwofe\testSDM.gdb\d2cu C;C;C;C;C D:\testSDM\gwofe\testSDM.gdb\TPts # 0.5 1
> Start Time: Fri Nov 24 08:24:52 2017
> Running script GrandWofe...
> 
> ========== arcsdm values  ==========
>                      ArcSdm 5.00.24 for ArcGis (Pro and Desktop)
> 
> Workspace:           D:\testSDM (FileSystem)
> Scratch workspace:   D:\testSDM\temp (FileSystem)
> Map Units:           meter
> Mask:                "sa_ide1" and it is FeatureClass
> Mask size:           154896.771772
> Cell Size:           50
> # Training Sites:    7
> Unit Cell Area:      1.0km^2, Cells in area: 154896.771772 
> Prior Probability:   0.000045
> Training Set:        D:\testSDM\gwofe\testSDM.gdb\TPts
> Study Area Raster:   D:\testSDM\gwofe\testSDM.gdb\sa_ide1
> Study Area Area:     154896.771772km^2
> ========== Starting GrandWofe ====================
> Calculating weights for D:\testSDM\gwofe\testSDM.gdb\d2ag (c)...
> GP ERRORS:
> 
> 
> ERROR 000354: The name contains invalid characters
> Failed to execute (CreateTable).
> 
> Unhandled exception caught
> Traceback (most recent call last):
>   File "D:\Tools\ArcSDM-master\ArcSDM-master\Toolbox\arcsdm\common.py", line 45, in execute_tool
>     func(self, parameters, messages)
>   File "D:\Tools\ArcSDM-master\ArcSDM-master\Toolbox\arcsdm\calculateweights.py", line 610, in Calculate
>     raise arcpy.ExecuteError;
> ExecuteError
> 
> Failed to execute (CalculateWeightsTool).
> 
> 
> PYTHON ERRORS:
> Traceback Info:
>   File "D:\Tools\ArcSDM-master\ArcSDM-master\Toolbox\arcsdm\grand_wofe_lr.py", line 116, in execute
>     Unit_Area__sq_km_, Missing_Data_Value)
> 
> Error Info:
>     <class 'arcgisscripting.ExecuteError'>: 
> 
> ERROR 000354: The name contains invalid characters
> Failed to execute (CreateTable).
> 
> Unhandled exception caught
> Traceback (most recent call last):
>   File "D:\Tools\ArcSDM-master\ArcSDM-master\Toolbox\arcsdm\common.py", line 45, in execute_tool
>     func(self, parameters, messages)
>   File "D:\Tools\ArcSDM-master\ArcSDM-master\Toolbox\arcsdm\calculateweights.py", line 610, in Calculate
>     raise arcpy.ExecuteError;
> ExecuteError
> 
> Failed to execute (CalculateWeightsTool).
> 
> 
> 
> Traceback (most recent call last):
>   File "<string>", line 149, in execute
>   File "D:\Tools\ArcSDM-master\ArcSDM-master\Toolbox\arcsdm\grand_wofe_lr.py", line 116, in execute
>     Unit_Area__sq_km_, Missing_Data_Value)
>   File "D:\Tools\ArcSDM-master\ArcSDM-master\Toolbox\ArcSDM.pyt", line 576, in CalculateWeightsTool
>     validation is performed.  This method is called whenever a parameter
> ExecuteError: 
> 
> ERROR 000354: The name contains invalid characters
> Failed to execute (CreateTable).
> 
> Unhandled exception caught
> Traceback (most recent call last):
>   File "D:\Tools\ArcSDM-master\ArcSDM-master\Toolbox\arcsdm\common.py", line 45, in execute_tool
>     func(self, parameters, messages)
>   File "D:\Tools\ArcSDM-master\ArcSDM-master\Toolbox\arcsdm\calculateweights.py", line 610, in Calculate
>     raise arcpy.ExecuteError;
> ExecuteError
> 
> Failed to execute (CalculateWeightsTool).
> 
> 
> Failed to execute (GrandWofe).
> Failed at Fri Nov 24 08:25:05 2017 (Elapsed Time: 13.18 seconds)

1. I fail to see where there is an issue with my file naming convention since it works for the other tools in SDM?

2. Once I put all the files into a gdb, it forced me to change the mask from a raster to a feature dataset in the Environment settings. I never had this issue before I put things into a gdb, and have always successfully used a raster as the mask. It's problematic if it's forcing you to modify your Environment settings half way through a project. 
![image](https://user-images.githubusercontent.com/32659237/33186884-2b9983d8-d0f2-11e7-9961-9230b7d554c3.png)

**Comment by trotor** [comment]
Reformatted lots of things - trying 5.00.27 please try
