### ISSUE TITLE
Logistic Regression: NoData and number of map limits

### ISSUE THREAD

**Issue by tachyon-work** [gtkfi/ArcSDM#70]
Two issues with LR analysis:
1. Output map excludes anything with NoData areas. Any area with NoData in one of the input maps comes out with a post probability value of 0. Can this be remedied? Problem occurs on both 10.3.1 and 10.5.

2. Appears to be a limit on the number of input maps/unique conditions that the LR tool can handle. Can this be remedied? Problem occurs on both 10.3.1 and 10.5.

**Comment by tachyon-work** [comment]
I have an explanation for the first error:
From existing ArcSDM documentation on Unicamp website:

> **Missing Data**
> Logistic regression does not process missing data directly. Instead an area weighted mean of the known class values within the study area is calculated for each evidential theme that contains missing data and substituted for the missing data class. For binary themes that have been generated by the expansion of multi-class free data, the area weighted mean is between 0 and 1.

The problem is that if you have a binary map with all the TP in one class (perfect correlation) and an additional NoData class, the "area weighted mean of the known class values" will be 0 (unless you manually manipulate the weights), so it sets the weight for the NoData class to 0. Which means when it starts integrating maps, if one map has a weight of 0, the output map will have a weight of 0. I've had a look at the python script for LogisticRegressionAll.py and can see the code starting on line 328 where this issue gets addressed. We need an alternative solution, because this workaround in the code seems to be what is causing the inaccurate LR pprb maps.

**Comment by tachyon-work** [comment]
This also appears to trace back to the sdmlr.exe executable that the LogisticRegressionAll script calls. Without access to the source code that was used to compile that executable, I can't see how this can be fixed. There's another bug report that also comes down to an issue with that exe file, so I think it's going to be necessary to track down that source code from the original SDM developers in order to fix it.

**Comment by trotor** [comment]
Update: Some improvements here too while working on grand wofe
