### ISSUE TITLE
Experimental toolbox doesn't work on Arcgis pro

### ISSUE THREAD

**Issue by trotor** [gtkfi/ArcSDM#72]
Even after installation of scikit-learn, toolbox fails to load:
>"%PROGRAMFILES%\ArcGIS\Pro\bin\Python\Scripts\proenv"

>conda install scikit-learn

Parsing error: 
Traceback (most recent call last):
  File "<string>", line 13, in <module>
  File "C:\ArcSDM\Toolbox\arcsdm\ModelTrain.py", line 29, in <module>
    from weight_boosting import BrownBoostClassifier
ImportError: No module named 'weight_boosting'

**Comment by trotor** [comment]
Sidenote, ESRI conda channel only cvontains scikit-learn 18.1
Trying:
conda install -c anaconda scikit-learn

**Comment by trotor** [comment]
New dependency **pyparsing** : 
>conda install pyparsing

**Comment by trotor** [comment]
Seems like manual update to this gets overriden by ESRI continuum/Anadonda repo. Querying ESRI support

**Comment by trotor** [comment]
ArcGis pro is missing Scikit-learn but this can be fixed like this:
First- 
•	Open the command line as an administrator
•	Change directories to C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Scripts
•	Use pip commands to uninstall current version of scikit-learn (pip uninstall scikit-learn) 
•	Once uninstalled reinstall again using pip command (pip install -U scikit-learn)
•	This should install again at the current version 
o	A good way to double check would be to navigate to C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages and see if the old package was removed and the correct version installed
Second, we will need to create a new environment variable for ArcGIS Pro: 
•	Close out of ArcGIS Pro
•	Navigate to the Start Menu > All Programs >  ArcGIS > ArcGIS Pro > right-click and run Python Command Prompt as Administrator 
o	If using Windows 10, simply type in Python Command Prompt > right click> Open File Location> right-click and run Python Command Prompt as Administrator
•	Once the command prompt opens up, type in conda create --name my_new_pro_env python=3.6
•	Once the new variable is created, activate it by typing in activate my_new_pro_env
•	Once activated, install the arcgis package by typing in conda install -c esri arcgis
•	Once this is done installing, close out of the command prompt and open ArcGIS Pro again
•	Navigate to Project > Python > change project environment drop-down to my_new_pro_env
•	Select Add Package > find scikit-learn and it should be at version .19.0
•	Add package

**Comment by yeomo** [comment]
I have installed ArcGIS Pro and added the toolboxes, however, I got the following error:

```
Traceback (most recent call last):
  File "<string>", line 8, in <module>
  File "F:\ArcSDM\Toolbox\arcsdm\AdaboostBestParameters.py", line 5, in <module>
    from sklearn.ensemble import AdaBoostClassifier
ModuleNotFoundError: No module named 'sklearn'
```

I then followed your above instructions which worked well until I re-entered ArcGIS Pro to change the project environment. I did this in Python Package Manager -> Manage Environments. When I click another env I get a message in the bottom corner saying "failed".

I googled how to switch environments outside of ArcGIS Pro and found that a batch file called proswap exists in the C:\Program Files\ArcGIS\Pro\bin\Python\Scripts directory, however, this generates the following error:

```
Traceback (most recent call last):
  File "proswap.py", line 110, in <module>
    if os.path.exists(os.path.join(local_env_path, input_env)):
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\ntpath.py", line 75, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

I have since reinstalled ArcGIS Pro and anaconda but this has not changed anything.

To me, and I am no expert, "os.path" sounds like the operating system path? Could there be an error in the PATH? 

Any help would be greatly appreciated, I know this is perhaps a very specific problem, I just need to run a few models in ArcSDM to finish my PhD...

**Comment by trotor** [comment]
Oh.... there were indeed some problems related when isntalling sklearn
and/or required packages....

Sorry that I forgot this and mislead you to think it could work - For
version 2.0 I have written "Experimental tools toolbar doesn't currently
work on ArcGis Pro (no scikit-learn package available for python on default
conda channels)"

I don't currently have time to debug this but I try to contribute ASAP.   I
think I should try it again, it was for 2.0.

**Comment by yeomo** [comment]
No worries.

To clarify, these problems have occurred using ArcGIS Pro 2.1.3. 

I will look out for the next commit :)
