### ISSUE TITLE
Calculate Response crashes (including to desktop) in ArcGIS Pro, failing at MDVar raster creation

### ISSUE THREAD

**Issue by DarthSysmon** [gtkfi/ArcSDM#73]
Hi there. 

I have run a few tests in ArcGIS Pro, creating a handful of weights tables for a set of binary and ternary rasters. The Calculate Weights tool work as well in Pro as in 10.5.

However, the Calculate Response tool causes a crash to desktop (Serious Application Error, I believe ArcGIS Pro calls it). May have gotten around it by recreating rasters in ArcGIS Pro and exporting point data as well. It still fails though, when creating the MDVar raster. Error dump below.

Cheers,
Simon

 
Parameters
Input Raster Layer(s)	aubicu3
Input weights tables	E:\Projects\GTK\SDMTest\Working\aubicu3_CT.dbf
Training sites	TC_TPs
Ignore missing data	
Missing data value	-99
Unit area (km^2)	1
Output post probablity raster	E:\Projects\GTK\SDMTest\Working\test1_pprb
Output standard deviation raster	E:\Projects\GTK\SDMTest\Working\test1_std
Output MD variance raster	E:\Projects\GTK\SDMTest\Working\test1_MDvar
Output Total Std Deviation Raster	E:\Projects\GTK\SDMTest\Working\test1_Tstd
Output confidence raster	E:\Projects\GTK\SDMTest\Working\test1_conf
 
Messages
Start Time: Monday, 6 November 2017 3:20:41 PM
Running script CalculateResponse...
Reloaded arcsdm modules
========== arcsdm values  ==========
ArcSdm 5.00.23 for ArcGis (Pro and Desktop)
Workspace:           E:\Projects\GTK\SDMTest\Working (FileSystem)
Scratch workspace:   E:\Projects\GTK\SDMTest\Temp (FileSystem)
Map Units:           meter
Mask:                "tc_sa" and it is RasterLayer
Mask size:           25537.2175
Cell Size:           50
# Training Sites:    31
Unit Cell Area:      1.0km^2, Cells in area: 25537.2175
Prior Probability:   0.001214
Training Set:        E:\Projects\GTK\SDMTest\Working\TC_TPs.shp
Study Area Raster:   E:\Projects\GTK\SDMTest\Working\tc_sa
Study Area Area:     25537.2175km^2
===================== Starting calculate response =====================
Study Area:          25537.2175
# training points:   31
Prior_prob:          0.0012139145543166557
Input rasters: ['aubicu3']
Input rasters: ['aubicu3']
Creating weight rasters
=========================================
Processing aubicu3
Temp_Raster=E:\Projects\GTK\SDMTest\Temp\temp_raster4
Wts_Table=E:\Projects\GTK\SDMTest\Working\aubicu3_CT.dbf
Output_Raster: E:\Projects\GTK\SDMTest\Temp\aubicu3_W0
Getting Post Logit raster...
=========================================
Input_data_str: "E:\Projects\GTK\SDMTest\Temp\aubicu3_W0"
InexpressionPlog: -6.712690320470657 + "E:\Projects\GTK\SDMTest\Temp\aubicu3_W0"
Creating Post Probability Raster...
=========================================
InExpression 1 ====> Exp(-6.712690320470657 + "E:\Projects\GTK\SDMTest\Temp\aubicu3_W0") / (1.0 + Exp(-6.712690320470657 + "E:\Projects\GTK\SDMTest\Temp\aubicu3_W0"))
Postprob: E:\Projects\GTK\SDMTest\Working\test1_pprb
Start Time: Monday, 6 November 2017 3:20:45 PM
Exp(-6.712690320470657 + Raster(r"E:\Projects\GTK\SDMTest\Temp\aubicu3_W0")) / (1.0 + Exp(-6.712690320470657 + Raster(r"E:\Projects\GTK\SDMTest\Temp\aubicu3_W0")))
Succeeded at Monday, 6 November 2017 3:20:48 PM (Elapsed Time: 3.14 seconds)
Creating STD rasters...
=========================================
Processing aubicu3
OutputRaster:E:\Projects\GTK\SDMTest\Temp\aubicu3_S0 exists: 0
RasterLayer=OutRas_lyr2
Temp_Raster=E:\Projects\GTK\SDMTest\Temp\temp_raster5
E:\Projects\GTK\SDMTest\Temp\aubicu3_S0
Creating Post Probability STD Raster...
=========================================
InExpression 2 ====> "E:\Projects\GTK\SDMTest\Temp\aubicu3_S0"
Start Time: Monday, 6 November 2017 3:20:51 PM
ApplyEnvironment(r"E:\Projects\GTK\SDMTest\Temp\aubicu3_S0")
Succeeded at Monday, 6 November 2017 3:20:52 PM (Elapsed Time: 1.33 seconds)
Unhandled exception caught
Traceback (most recent call last):
  File "E:\Projects\GTK\ArcSDM-master\Toolbox\arcsdm\calculateresponse.py", line 425, in Execute
    import missingdatavar_func
ImportError: No module named 'missingdatavar_func'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Projects\GTK\ArcSDM-master\Toolbox\arcsdm\common.py", line 45, in execute_tool
    func(self, parameters, messages)
  File "E:\Projects\GTK\ArcSDM-master\Toolbox\arcsdm\calculateresponse.py", line 519, in Execute
    str(sys.exc_type)+ ": " + str(sys.exc_value) + "\n"
AttributeError: module 'sys' has no attribute 'exc_type'
Completed script CalculateResponse...
Failed to execute (CalculateResponse).
Failed at Monday, 6 November 2017 3:20:52 PM (Elapsed Time: 11.95 seconds)

**Comment by tachyon-work** [comment]
It's trying to do a divide by zero because you only put one input map into your calculate response.

Shouldn't crash ArcMap though, should just spit an error at you.

**Comment by DarthSysmon** [comment]
Brainfart, closing.
