### ISSUE TITLE
Calculate Response missing data var failure in ArcGIS Pro

### ISSUE THREAD

**Issue by DarthSysmon** [gtkfi/ArcSDM#74]
Hi there.

Seems the SDM toolbox works well out of a geodatabase in ArcGIS Pro, but only if using files saved by ArcGIS Pro - older formats need to be converted. And the whole things become a bit wobbly if anything at all live outside geodatabases.

Running Calculate Response on a model with 3 maps, one of which has missing data (-99), caused a failure (unhandled exception). Looks like it can't find the missingdatavar_func module:

 
Parameters
Input Raster Layer(s)	Rocksbin;Soilsbin;Faultsbin
Input weights tables	E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTest.gdb\Rocksbin_CT;E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTest.gdb\Soilsbin_CT;E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTest.gdb\Faultsbin_CT
Training sites	MerredinTP
Ignore missing data	
Missing data value	-99
Unit area (km^2)	0.7
Output post probablity raster	E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTest.gdb\Test1_pprb
Output standard deviation raster	E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTest.gdb\Test1_std
Output MD variance raster	E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTest.gdb\Test1_MDvar
Output Total Std Deviation Raster	E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTest.gdb\Test1_Tstd
Output confidence raster	E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTest.gdb\Test1_conf
 
Messages
Start Time: Tuesday, 7 November 2017 12:48:24 PM
Running script CalculateResponse...
Reloaded arcsdm modules
========== arcsdm values  ==========
ArcSdm 5.00.23 for ArcGis (Pro and Desktop)
Workspace:           E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTest.gdb (LocalDatabase)
Scratch workspace:   E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb (LocalDatabase)
Map Units:           meter
Mask:                "SAraster" and it is RasterLayer
Mask size:           19494.165
Cell Size:           50
# Training Sites:    14
Unit Cell Area:      0.7km^2, Cells in area: 27848.807142857146
Prior Probability:   0.000503
Training Set:        E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTest.gdb\MerredinTP
Study Area Raster:   E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTest.gdb\SAraster
Study Area Area:     19494.165km^2
===================== Starting calculate response =====================
Study Area:          27848.807142857146
# training points:   14
Prior_prob:          0.0005027145302196836
Input rasters: ['Rocksbin', 'Soilsbin', 'Faultsbin']
Input rasters: ['Rocksbin', 'Soilsbin', 'Faultsbin']
Creating weight rasters
=========================================
Processing Rocksbin
Temp_Raster=E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\temp_raster0
Wts_Table=E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTest.gdb\Rocksbin_CT
Output_Raster: E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Rocksbin_W0
Processing Soilsbin
Temp_Raster=E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\temp_raster1
Wts_Table=E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTest.gdb\Soilsbin_CT
Output_Raster: E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Soilsbin_W0
Processing Faultsbin
Temp_Raster=E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\temp_raster2
Wts_Table=E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTest.gdb\Faultsbin_CT
Output_Raster: E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Faultsbin_W0
Getting Post Logit raster...
=========================================
Input_data_str: "E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Rocksbin_W0" + "E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Soilsbin_W0" + "E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Faultsbin_W0"
InexpressionPlog: -7.594985242394087 + ("E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Rocksbin_W0" + "E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Soilsbin_W0" + "E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Faultsbin_W0")
Creating Post Probability Raster...
=========================================
InExpression 1 ====> Exp(-7.594985242394087 + ("E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Rocksbin_W0" + "E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Soilsbin_W0" + "E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Faultsbin_W0")) / (1.0 + Exp(-7.594985242394087 + ("E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Rocksbin_W0" + "E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Soilsbin_W0" + "E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Faultsbin_W0")))
Postprob: E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTest.gdb\Test1_pprb
Start Time: Tuesday, 7 November 2017 12:48:45 PM
Exp(-7.594985242394087 + (Raster(r"E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Rocksbin_W0") + Raster(r"E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Soilsbin_W0") + Raster(r"E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Faultsbin_W0"))) / (1.0 + Exp(-7.594985242394087 + (Raster(r"E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Rocksbin_W0") + Raster(r"E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Soilsbin_W0") + Raster(r"E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Faultsbin_W0"))))
Succeeded at Tuesday, 7 November 2017 12:48:54 PM (Elapsed Time: 8.96 seconds)
Creating STD rasters...
=========================================
Processing Rocksbin
OutputRaster:E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Rocksbin_S0 exists: 0
RasterLayer=OutRas_lyr2
Temp_Raster=E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\temp_raster3
E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Rocksbin_S0
Processing Soilsbin
OutputRaster:E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Soilsbin_S0 exists: 0
RasterLayer=OutRas_lyr2
Temp_Raster=E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\temp_raster4
E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Soilsbin_S0
Processing Faultsbin
OutputRaster:E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Faultsbin_S0 exists: 0
RasterLayer=OutRas_lyr2
Temp_Raster=E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\temp_raster5
E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Faultsbin_S0
Creating Post Probability STD Raster...
=========================================
Sum_args: Square("E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Rocksbin_S0") + Square("E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Soilsbin_S0") + Square("E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Faultsbin_S0")
=========================================
InExpression = SquareRoot(Square("E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTest.gdb\Test1_pprb") * (0.07142857142857142 +(Square("E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Rocksbin_S0") + Square("E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Soilsbin_S0") + Square("E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Faultsbin_S0"))))
InExpression 2 ====> SquareRoot(Square("E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTest.gdb\Test1_pprb") * (0.07142857142857142 +(Square("E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Rocksbin_S0") + Square("E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Soilsbin_S0") + Square("E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Faultsbin_S0"))))
Start Time: Tuesday, 7 November 2017 12:49:14 PM
SquareRoot(Square(Raster(r"E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTest.gdb\Test1_pprb")) * (0.07142857142857142 +(Square(Raster(r"E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Rocksbin_S0")) + Square(Raster(r"E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Soilsbin_S0")) + Square(Raster(r"E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Faultsbin_S0")))))
Succeeded at Tuesday, 7 November 2017 12:49:21 PM (Elapsed Time: 7.41 seconds)
Unhandled exception caught
Traceback (most recent call last):
  File "E:\Projects\GTK\ArcSDM-master\Toolbox\arcsdm\calculateresponse.py", line 425, in Execute
    import missingdatavar_func
ImportError: No module named 'missingdatavar_func'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Projects\GTK\ArcSDM-master\Toolbox\arcsdm\common.py", line 45, in execute_tool
    func(self, parameters, messages)
  File "E:\Projects\GTK\ArcSDM-master\Toolbox\arcsdm\calculateresponse.py", line 519, in Execute
    str(sys.exc_type)+ ": " + str(sys.exc_value) + "\n"
AttributeError: module 'sys' has no attribute 'exc_type'
Completed script CalculateResponse...
Failed to execute (CalculateResponse).
Failed at Tuesday, 7 November 2017 12:49:21 PM (Elapsed Time: 57.80 seconds)

**Comment by trotor** [comment]
This is very curious as there clearly is that file - will check... did you run this on ArcGis pro or desktop?

**Comment by DarthSysmon** [comment]
This is ArcGIS Pro 2.0.1.

Cheers,
S

**Comment by DarthSysmon** [comment]
Same failure using build .24, this time with 4 maps (checking the perfect correlation issue, thanks for fixing it):

Running script CalculateResponse...
Reloaded arcsdm modules
========== arcsdm values  ==========
ArcSdm 5.00.24 for ArcGis (Pro and Desktop)
Workspace:           E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTest.gdb (LocalDatabase)
Scratch workspace:   E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb (LocalDatabase)
Map Units:           meter
Mask:                "SAraster" and it is RasterLayer
Mask size:           19494.165
Cell Size:           50
# Training Sites:    14
Unit Cell Area:      0.7km^2, Cells in area: 27848.807142857146
Prior Probability:   0.000503
Training Set:        E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTest.gdb\MerredinTP
Study Area Raster:   E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTest.gdb\SAraster
Study Area Area:     19494.165km^2
===================== Starting calculate response =====================
Study Area:          27848.807142857146
# training points:   14
Prior_prob:          0.0005027145302196836
Input rasters: ['Struc0p34_bin', 'Litho_bin', 'Faults15k_bin', 'Gold1k_bin']
Input rasters: ['Struc0p34_bin', 'Litho_bin', 'Faults15k_bin', 'Gold1k_bin']
Creating weight rasters
=========================================
Processing Struc0p34_bin
Temp_Raster=E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\temp_raster6
Wts_Table=E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTest.gdb\Struc0p34_bin_CT
Output_Raster: E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Struc0p34__W0
Processing Litho_bin
Temp_Raster=E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\temp_raster7
Wts_Table=E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTest.gdb\Litho_bin_CT
Output_Raster: E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Litho_bin_W0
Processing Faults15k_bin
Temp_Raster=E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\temp_raster8
Wts_Table=E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTest.gdb\Faults15k_bin_CT
Output_Raster: E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Faults15k__W0
Processing Gold1k_bin
Temp_Raster=E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\temp_raster9
Wts_Table=E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTest.gdb\Gold1k_bin_CT
Output_Raster: E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Gold1k_bin_W0
Getting Post Logit raster...
=========================================
Input_data_str: "E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Struc0p34__W0" + "E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Litho_bin_W0" + "E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Faults15k__W0" + "E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Gold1k_bin_W0"
InexpressionPlog: -7.594985242394087 + ("E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Struc0p34__W0" + "E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Litho_bin_W0" + "E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Faults15k__W0" + "E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Gold1k_bin_W0")
Creating Post Probability Raster...
=========================================
InExpression 1 ====> Exp(-7.594985242394087 + ("E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Struc0p34__W0" + "E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Litho_bin_W0" + "E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Faults15k__W0" + "E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Gold1k_bin_W0")) / (1.0 + Exp(-7.594985242394087 + ("E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Struc0p34__W0" + "E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Litho_bin_W0" + "E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Faults15k__W0" + "E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Gold1k_bin_W0")))
Postprob: E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTest.gdb\Test_pprb
Start Time: Monday, 13 November 2017 10:44:39 AM
Exp(-7.594985242394087 + (Raster(r"E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Struc0p34__W0") + Raster(r"E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Litho_bin_W0") + Raster(r"E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Faults15k__W0") + Raster(r"E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Gold1k_bin_W0"))) / (1.0 + Exp(-7.594985242394087 + (Raster(r"E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Struc0p34__W0") + Raster(r"E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Litho_bin_W0") + Raster(r"E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Faults15k__W0") + Raster(r"E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Gold1k_bin_W0"))))
Succeeded at Monday, 13 November 2017 10:44:52 AM (Elapsed Time: 12.66 seconds)
Creating STD rasters...
=========================================
Processing Struc0p34_bin
OutputRaster:E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Struc0p34_S0 exists: 0
RasterLayer=OutRas_lyr2
Temp_Raster=E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\temp_raster10
E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Struc0p34_S0
Processing Litho_bin
OutputRaster:E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Litho_bin_S0 exists: 0
RasterLayer=OutRas_lyr2
Temp_Raster=E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\temp_raster11
E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Litho_bin_S0
Processing Faults15k_bin
OutputRaster:E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Faults15k_S0 exists: 0
RasterLayer=OutRas_lyr2
Temp_Raster=E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\temp_raster12
E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Faults15k_S0
Processing Gold1k_bin
OutputRaster:E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Gold1k_bi_S0 exists: 0
RasterLayer=OutRas_lyr2
Temp_Raster=E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\temp_raster13
E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Gold1k_bi_S0
Creating Post Probability STD Raster...
=========================================
Sum_args: Square("E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Struc0p34_S0") + Square("E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Litho_bin_S0") + Square("E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Faults15k_S0") + Square("E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Gold1k_bi_S0")
=========================================
InExpression = SquareRoot(Square("E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTest.gdb\Test_pprb") * (0.07142857142857142 +(Square("E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Struc0p34_S0") + Square("E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Litho_bin_S0") + Square("E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Faults15k_S0") + Square("E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Gold1k_bi_S0"))))
InExpression 2 ====> SquareRoot(Square("E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTest.gdb\Test_pprb") * (0.07142857142857142 +(Square("E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Struc0p34_S0") + Square("E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Litho_bin_S0") + Square("E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Faults15k_S0") + Square("E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Gold1k_bi_S0"))))
Start Time: Monday, 13 November 2017 10:45:29 AM
SquareRoot(Square(Raster(r"E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTest.gdb\Test_pprb")) * (0.07142857142857142 +(Square(Raster(r"E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Struc0p34_S0")) + Square(Raster(r"E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Litho_bin_S0")) + Square(Raster(r"E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Faults15k_S0")) + Square(Raster(r"E:\Projects\GTK\SDMTest\GeoDBTest\GeoDBTemp.gdb\Gold1k_bi_S0")))))
Succeeded at Monday, 13 November 2017 10:45:40 AM (Elapsed Time: 10.21 seconds)
Unhandled exception caught
Traceback (most recent call last):
  File "E:\Projects\GTK\ArcSDM-master\Toolbox\arcsdm\calculateresponse.py", line 425, in Execute
    import missingdatavar_func
ImportError: No module named 'missingdatavar_func'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Projects\GTK\ArcSDM-master\Toolbox\arcsdm\common.py", line 45, in execute_tool
    func(self, parameters, messages)
  File "E:\Projects\GTK\ArcSDM-master\Toolbox\arcsdm\calculateresponse.py", line 519, in Execute
    str(sys.exc_type)+ ": " + str(sys.exc_value) + "\n"
AttributeError: module 'sys' has no attribute 'exc_type'
Completed script CalculateResponse...
Failed to execute (CalculateResponse).

**Comment by artolaiho** [comment]
calculateresponse.py has typo:
"import missingdatavar_func" must be: "import arcsdm.missingdatavar_func"

missingdatavar_func.py has four typos:
- "from floatingrasterarray ..." must be "from arcsdm.floatingrasterarray ..."
- "except Exception,Msg:" is invalid syntax, ",Msg" has to be removed
- "print pymsg" must be "print (pymsg)"
- "print msgs" must be "print (msgs)"

**Comment by artolaiho** [comment]
I have fixed those typos. Download whole arcSDM packet from arto-dev branch. See readme.

**Comment by artolaiho** [comment]
Load the newest version of ArcSDM (V5.02) and test again. If the problem persists, reopen this issue.
ArcSDM Toolbox is now working at least ArcGIS Desktop 10.6.1, ArcGIS Pro 2.5 and ArcGIS Pro 2.6.
