### ISSUE TITLE
GrandWofe: logistic regression error

### ISSUE THREAD

**Issue by VesaNy** [gtkfi/ArcSDM#78]
GrandWofe seems to crash when it starts logistic regression:

Executing (Grand WOFE): GrandWofe GW1_orog_Au C:\arcsdm\MPM_tests\grandwofe\GrandWofeTest.gdb\Rc_AppRes;C:\arcsdm\MPM_tests\grandwofe\GrandWofeTest.gdb\Rc_dst2gravwrm;C:\arcsdm\MPM_tests\grandwofe\GrandWofeTest.gdb\Rc_dst_mstru;C:\arcsdm\MPM_tests\grandwofe\GrandWofeTest.gdb\Rc_hp_co;C:\arcsdm\MPM_tests\grandwofe\GrandWofeTest.gdb\Rc_hp_cu;C:\arcsdm\MPM_tests\grandwofe\GrandWofeTest.gdb\Rc_hp_fe;C:\arcsdm\MPM_tests\grandwofe\GrandWofeTest.gdb\Rc_hp_te;metam_facies;AuPermissiveAreaUpdated o;o;o;o;o;o;o;c;c OrogenicAu # 2 1
Start Time: Fri Dec 15 10:06:58 2017
Running script GrandWofe...

========== arcsdm values  ==========
                     ArcSdm 5.00.25 for ArcGis (Pro and Desktop)

Workspace:           C:\arcsdm\MPM_tests\grandwofe\GrandWofeTest.gdb (LocalDatabase)
Scratch workspace:   C:\arcsdm\MPM_tests\grandwofe\GrandWofeTest.gdb (LocalDatabase)
Map Units:           meter
Mask:                "StudyArea" and it is FeatureLayer
Mask size:           98856.9550016
Cell Size:           50
# Training Sites:    42
Unit Cell Area:      1.0km^2, Cells in area: 98856.9550016 
Prior Probability:   0.000425
Training Set:        C:\arcsdm\LapinKaiku\LapinKaiku.gdb\OrogenicAu\OrogenicAu
Study Area Raster:   C:\arcsdm\LapinKaiku\LapinKaiku.gdb\StudyArea
Study Area Area:     98856.9550016km^2

========== Starting GrandWofe ====================
Calculating weights for C:\arcsdm\MPM_tests\grandwofe\GrandWofeTest.gdb\Rc_AppRes (o)...
     ...done
Result: C:\arcsdm\MPM_tests\grandwofe\GrandWofeTest.gdb\Rc_AppRes_GW1_orog_Au_CA

     ...done
Result: C:\arcsdm\MPM_tests\grandwofe\GrandWofeTest.gdb\Rc_AppRes_GW1_orog_Au_CD

Calculating weights for C:\arcsdm\MPM_tests\grandwofe\GrandWofeTest.gdb\Rc_dst2gravwrm (o)...
     ...done
Result: C:\arcsdm\MPM_tests\grandwofe\GrandWofeTest.gdb\Rc_dst2gravwrm_GW1_orog_Au_CA

     ...done
Result: C:\arcsdm\MPM_tests\grandwofe\GrandWofeTest.gdb\Rc_dst2gravwrm_GW1_orog_Au_CD

Calculating weights for C:\arcsdm\MPM_tests\grandwofe\GrandWofeTest.gdb\Rc_dst_mstru (o)...
     ...done
Result: C:\arcsdm\MPM_tests\grandwofe\GrandWofeTest.gdb\Rc_dst_mstru_GW1_orog_Au_CA

     ...done
Result: C:\arcsdm\MPM_tests\grandwofe\GrandWofeTest.gdb\Rc_dst_mstru_GW1_orog_Au_CD

Calculating weights for C:\arcsdm\MPM_tests\grandwofe\GrandWofeTest.gdb\Rc_hp_co (o)...
     ...done
Result: C:\arcsdm\MPM_tests\grandwofe\GrandWofeTest.gdb\Rc_hp_co_GW1_orog_Au_CA

     ...done
Result: C:\arcsdm\MPM_tests\grandwofe\GrandWofeTest.gdb\Rc_hp_co_GW1_orog_Au_CD

Calculating weights for C:\arcsdm\MPM_tests\grandwofe\GrandWofeTest.gdb\Rc_hp_cu (o)...
     ...done
Result: C:\arcsdm\MPM_tests\grandwofe\GrandWofeTest.gdb\Rc_hp_cu_GW1_orog_Au_CA

     ...done
Result: C:\arcsdm\MPM_tests\grandwofe\GrandWofeTest.gdb\Rc_hp_cu_GW1_orog_Au_CD

Calculating weights for C:\arcsdm\MPM_tests\grandwofe\GrandWofeTest.gdb\Rc_hp_fe (o)...
     ...done
Result: C:\arcsdm\MPM_tests\grandwofe\GrandWofeTest.gdb\Rc_hp_fe_GW1_orog_Au_CA

     ...done
Result: C:\arcsdm\MPM_tests\grandwofe\GrandWofeTest.gdb\Rc_hp_fe_GW1_orog_Au_CD

Calculating weights for C:\arcsdm\MPM_tests\grandwofe\GrandWofeTest.gdb\Rc_hp_te (o)...
     ...done
Result: C:\arcsdm\MPM_tests\grandwofe\GrandWofeTest.gdb\Rc_hp_te_GW1_orog_Au_CA

     ...done
Result: C:\arcsdm\MPM_tests\grandwofe\GrandWofeTest.gdb\Rc_hp_te_GW1_orog_Au_CD

Calculating weights for metam_facies (c)...
     ...done
Result: C:\arcsdm\MPM_tests\grandwofe\GrandWofeTest.gdb\metam_facies_GW1_orog_Au_CT

Calculating weights for AuPermissiveAreaUpdated (c)...
     ...done
Result: C:\arcsdm\MPM_tests\grandwofe\GrandWofeTest.gdb\AuPermissiveAreaUpdated_GW1_orog_Au_CT

------ Running tests... (0) ------
A: Response & Logistic Regression: C:\arcsdm\MPM_tests\grandwofe\GrandWofeTest.gdb\Rc_AppRes;C:\arcsdm\MPM_tests\grandwofe\GrandWofeTest.gdb\Rc_dst2gravwrm;C:\arcsdm\MPM_tests\grandwofe\GrandWofeTest.gdb\Rc_dst_mstru;C:\arcsdm\MPM_tests\grandwofe\GrandWofeTest.gdb\Rc_hp_co;C:\arcsdm\MPM_tests\grandwofe\GrandWofeTest.gdb\Rc_hp_cu;C:\arcsdm\MPM_tests\grandwofe\GrandWofeTest.gdb\Rc_hp_fe;C:\arcsdm\MPM_tests\grandwofe\GrandWofeTest.gdb\Rc_hp_te;metam_facies;AuPermissiveAreaUpdated,C:\arcsdm\MPM_tests\grandwofe\GrandWofeTest.gdb\Rc_AppRes_GW1_orog_Au_CA;C:\arcsdm\MPM_tests\grandwofe\GrandWofeTest.gdb\Rc_dst2gravwrm_GW1_orog_Au_CA;C:\arcsdm\MPM_tests\grandwofe\GrandWofeTest.gdb\Rc_dst_mstru_GW1_orog_Au_CA;C:\arcsdm\MPM_tests\grandwofe\GrandWofeTest.gdb\Rc_hp_co_GW1_orog_Au_CA;C:\arcsdm\MPM_tests\grandwofe\GrandWofeTest.gdb\Rc_hp_cu_GW1_orog_Au_CA;C:\arcsdm\MPM_tests\grandwofe\GrandWofeTest.gdb\Rc_hp_fe_GW1_orog_Au_CA;C:\arcsdm\MPM_tests\grandwofe\GrandWofeTest.gdb\Rc_hp_te_GW1_orog_Au_CA;C:\arcsdm\MPM_tests\grandwofe\GrandWofeTest.gdb\metam_facies_GW1_orog_Au_CT;C:\arcsdm\MPM_tests\grandwofe\GrandWofeTest.gdb\AuPermissiveAreaUpdated_GW1_orog_Au_CT

 Calculating response... 
       ...done
 Running logistic regression...
GP ERRORS:

ERROR 010069: Unable to open input raster(s).
ERROR 010067: Error in executing grid expression.
Failed to execute (Combine).

Traceback
  File "C:\ArcSDM_New\Toolbox\arcsdm\logisticregression.py", line 114, in Execute
    gp.Combine_sa(Input_Combine_rasters, thmUC)

Error Info:
ERROR 010069: Unable to open input raster(s).
ERROR 010067: Error in executing grid expression.
Failed to execute (Combine).

Unhandled exception caught
Traceback (most recent call last):
  File "C:\ArcSDM_New\Toolbox\arcsdm\common.py", line 45, in execute_tool
    func(self, parameters, messages)
  File "C:\ArcSDM_New\Toolbox\arcsdm\logisticregression.py", line 114, in Execute
    gp.Combine_sa(Input_Combine_rasters, thmUC)
ExecuteError: ERROR 010069: Unable to open input raster(s).
ERROR 010067: Error in executing grid expression.
Failed to execute (Combine).

Failed to execute (LogisticRegressionTool).

PYTHON ERRORS:
Traceback Info:
  File "C:\ArcSDM_New\Toolbox\arcsdm\grand_wofe_lr.py", line 222, in execute
    Output_Post_Probability_raster, Output_Standard_Deviation_raster, Output_LR_Confidence_raster)

Error Info:
    <class 'arcgisscripting.ExecuteError'>: 

ERROR 010069: Unable to open input raster(s).
ERROR 010067: Error in executing grid expression.
Failed to execute (Combine).

Traceback
  File "C:\ArcSDM_New\Toolbox\arcsdm\logisticregression.py", line 114, in Execute
    gp.Combine_sa(Input_Combine_rasters, thmUC)

Error Info:
ERROR 010069: Unable to open input raster(s).
ERROR 010067: Error in executing grid expression.
Failed to execute (Combine).

Unhandled exception caught
Traceback (most recent call last):
  File "C:\ArcSDM_New\Toolbox\arcsdm\common.py", line 45, in execute_tool
    func(self, parameters, messages)
  File "C:\ArcSDM_New\Toolbox\arcsdm\logisticregression.py", line 114, in Execute
    gp.Combine_sa(Input_Combine_rasters, thmUC)
ExecuteError: ERROR 010069: Unable to open input raster(s).
ERROR 010067: Error in executing grid expression.
Failed to execute (Combine).

Failed to execute (LogisticRegressionTool).

Traceback (most recent call last):
  File "<string>", line 149, in execute
  File "C:\ArcSDM_New\Toolbox\arcsdm\grand_wofe_lr.py", line 222, in execute
    Output_Post_Probability_raster, Output_Standard_Deviation_raster, Output_LR_Confidence_raster)
  File "C:\ArcSDM_New\Toolbox\ArcSDM.pyt", line 683, in LogisticRegressionTool
    """Modify the values and properties of parameters before internal
ExecuteError: 

ERROR 010069: Unable to open input raster(s).
ERROR 010067: Error in executing grid expression.
Failed to execute (Combine).

Traceback
  File "C:\ArcSDM_New\Toolbox\arcsdm\logisticregression.py", line 114, in Execute
    gp.Combine_sa(Input_Combine_rasters, thmUC)

Error Info:
ERROR 010069: Unable to open input raster(s).
ERROR 010067: Error in executing grid expression.
Failed to execute (Combine).

Unhandled exception caught
Traceback (most recent call last):
  File "C:\ArcSDM_New\Toolbox\arcsdm\common.py", line 45, in execute_tool
    func(self, parameters, messages)
  File "C:\ArcSDM_New\Toolbox\arcsdm\logisticregression.py", line 114, in Execute
    gp.Combine_sa(Input_Combine_rasters, thmUC)
ExecuteError: ERROR 010069: Unable to open input raster(s).
ERROR 010067: Error in executing grid expression.
Failed to execute (Combine).

Failed to execute (LogisticRegressionTool).

Failed to execute (Grand WOFE).
Failed at Fri Dec 15 10:36:40 2017 (Elapsed Time: 29 minutes 42 seconds)

**Comment by trotor** [comment]
Getting a bit ahead, changing it to newer arcpy:
Combining...C:\ArcSDM\work\MPM_Demo.gdb\rc_till_c_G14;C:\ArcSDM\work\MPM_Demo.gdb\rc_till_c_G15;C:\ArcSDM\work\MPM_Demo.gdb\rc_till_f_G5


Caught ExecuteError in logistic regression. Details:
ERROR 010158: Unable to open file c:\windows\system32\tmp8694.
ERROR 010067: Error in executing grid expression.
Failed to execute (Combine).

Traceback
  File "C:\ArcSDM\Toolbox\arcsdm\logisticregression.py", line 121, in Execute
    combined = arcpy.sa.Combine(Input_Combine_rasters)



Badnews: I have no idea why it tries to write to system32 tmp directory...

**Comment by trotor** [comment]
Some improvements and fixes on 5.00.26

**Comment by trotor** [comment]
5.00.27 Could be fixed - please try

**Comment by artolaiho** [comment]
Can you try again using modified tools (calculateweights.py, calculateresponse.py, logisticregression.py and grand_wofe_lr.py) on arto-dev branch.

**Comment by artolaiho** [comment]
Load the newest version of ArcSDM (V5.02) and test again. If the problem persists, reopen this issue.
