### ISSUE TITLE
Multiple setup issues

### ISSUE THREAD

**Issue by tachyon-work** [gtkfi/ArcSDM#79]
Setup in 10.3.1, trying to run a simple calculate weights:

1. There is a significant change from the previous SDM in that apparently now all the environment settings require you to have everything stored in a gdb. Historically you just set the environment settings to the relevant raster and the SDM worked. Now, if you don't have all your files in a gdb, everything fails to run. This needs to be made explicit in the documentation, as this has never been necessary in the past.
I appreciate that this SDM is being designed to work in ArcGIS Pro, and I know that there are differences in the geodatabase structures between Pro and previous versions. So if SDM is no longer going to work in anything prior to Pro, can you please let us know.
![image](https://user-images.githubusercontent.com/32659237/34501355-6067ec8a-f073-11e7-9f38-071214d49951.png)

2. Tools fail to run unless your mask is set to a polygon in a gdb. This means you are now required to have a different snap raster and mask. This is a serious fundamental problem, because the areas are going to be marginally different, cell counts will be off, and this messes with the statistics. The mask has to be allowed to be a raster. This is pretty urgent.

3. Even when you do change the above to get past the errors that pop up, you get the following error anyway:
![image](https://user-images.githubusercontent.com/32659237/34501597-74d67b18-f074-11e7-8ae3-136e76b45c7a.png)
It looks like there might be a typo in the code somewhere. 

The second issue is fundamental and is of serious concern.

**Comment by trotor** [comment]
Thanks for the commments! Everything should work in arcmap and I personally even run them on here. And everything should work without GDB too - I will re-request non-gdb demodata again from the demodata team, I don't have it currently available. 

RasterLayers are supported, raster datasets are not - there is no real reason for that except that they behaved differently from rasterlayers and I disabled them because of my work schedule. I can focus on them as soon as I get working example from the demodata team.

Dwrite line issue fixed on v 28

**Comment by tachyon-work** [comment]
Ok, thanks for the info. I created a raster layer from the raster dataset, and now I get this:
![image](https://user-images.githubusercontent.com/32659237/34534566-7ad17464-f123-11e7-92d9-d26ad768124c.png)

It won't read the info from the layer file?

**Comment by tachyon-work** [comment]
I downloaded your GTK demo data, because I wanted to see what was going on. If I open up your MPM_DemoData mxd to examine the environment settings so that I can make sure I'm setting mine up in a similar way with my data, I notice there's a few issues:
1. You don't have output coordinates or the processing extent set - these are critical to ensure correct ouput:
![capture1](https://user-images.githubusercontent.com/32659237/34539332-f0f475c2-f134-11e7-8082-39b957bcb589.PNG)

2. The raster analysis settings are not set properly. The cell size isn't set (it needs to be), and the mask has to be a raster for the analysis to work properly. The demo data mxd has it set to a vector layer. This will invalidate the statistics the tools generate because it messes up the cell alignment and cell counts. It needs to be a raster to get accurate results.
![capture2](https://user-images.githubusercontent.com/32659237/34539366-0c9c3454-f135-11e7-9ffd-a4767025f457.PNG)

This may explain why you're not able to replicate the errors that myself and @DarthSysmon are getting.

**Comment by trotor** [comment]
I will take a look at there raster dataset issues asap. I think it could be
that rasterdataset (file?) stored in fgdb is rasterlayer and there were
some differences how they are accessed via arcpy.

**Comment by tachyon-work** [comment]
My suggestion for the raster mask is to simply export one of your pre-existing grids to a new study_area raster in the gdb and use that to define the mask ans snap raster. That being said, if you update your environment settings accordingly you then run into the aforementioned error where it says you can't have a raster dataset as a mask...

**Comment by trotor** [comment]
The problem lies somewhere in counting mask size for prior-probability. Now fixed but might not work on all inputs. output coordinate system and extent shouldn't have effect anymore, I have made it to obey "same as input" on most places. But will forward the suggestion to demodata team and will test with that .

**Comment by tachyon-work** [comment]
Output coordinate system: this assumes all your input data is in the same projection. This is rarely the case in reality. If anything happens to be in a different projection, this will end up causing problems when you start doing raster processing. Even in your demo data, not everything is in the same projection. I can see some rasters are in a Finnish projection, some are in some ERTS transverse mercator projection. To ensure consistent raster outputs for any raster processing (either SDM or Spatial Analyst), the output coordinate system needs to be set. You can't have it set to "same as input" unless your inputs are all the same. They're not the same.

Extent: As above - you're assuming the extent of all your inputs is the same. And you're also assuming you have no missing data areas. While the rasters in your demo data all appear to have the same extent (and that's fine), it's very easy to create one from the included vector data that doesn't, as well as one that includes missing data. This has to be tested, because it's one of the fundamental issues that has to be dealt with in SDM. At the very least the snap raster has to be set.

**Comment by trotor** [comment]
Okay, very good points, I will take this into account. And special thanks
for pointing out that our demodata still contains some non-standard data,
it should not. We are obligated to use ETRS EUREF on all of our data and
will fix it!

T

**Comment by tachyon-work** [comment]
Most appear to be in EUREF_FIN_TMFIN, but the Geol_grid maps are in ETRS_1989_Transverse_Mercator.

If you take a look at the Era_200k raster for example, it has different extents to other rasters.

**Comment by trotor** [comment]
New demodata set uploaded. Are other points still valid?

**Comment by tachyon-work** [comment]
That updated code I sent to your team a while back fixed it. This can be closed.
