### ISSUE TITLE
what is the Information Rasters in the apply model?how to do with it?

### ISSUE THREAD

**Issue by canglangshushu** [gtkfi/ArcSDM#82]

**Comment by trotor** [comment]
Hi, are you talking about the demo models in demo data package?

**Comment by trotor** [comment]
Hi, thanks for your input! Is RF tool you are talking about the Random forest tool? The help can be found by clicking the tool with rightclick and selecting help. 

Does this information help you?

**Comment by canglangshushu** [comment]
yes，I can do it well now，thank you
