### ISSUE TITLE
Grand wofe fails in Arcgis Pro

### ISSUE THREAD

**Issue by trotor** [gtkfi/ArcSDM#87]
Working on Tachyon-work patches on merge-tmp branch but currently unable to run.

**Comment by trotor** [comment]
#85

**Comment by DarthSysmon** [comment]
Pro has a long way to go before the Spatial Analysis tools are of any use. In the version I tested, there was no ability to do anything but equal distance reclassification, for example.

**Comment by trotor** [comment]
I will merge changes made by @tachyon-work today and will "close" these as bugs and change them to can't implement or future work. It really does seem futile to make this work in ArcGis pro. Thank you for your comments! I can add you both as contributors to the project so you can directly make changes or pullreqeusts to the master branch - there is small file called arcsdm_version.txt inside the arcsdm directory that contains authors and top line is shown as version info - please update that and front page readme.md when doing changes. Thanks!

**Comment by trotor** [comment]
![image](https://user-images.githubusercontent.com/10844537/39360053-3dc9d7e0-4a25-11e8-8042-a6b28ddb3c43.png)


Goes through with VALID inputs with FILE workspaces and files.

**Comment by trotor** [comment]
Removing bug label - this might be more of "very very hard for user to find why it fails" and needs more warnings.

**Comment by trotor** [comment]
It completely fails on miscreated weight tables instead of giving warning - this is parameter transfer issue from calculate weights to grandwofe.

**Comment by trotor** [comment]
Most likely doesn't fail anymore - workaround found.
