### ISSUE TITLE
Training sites reduction tool

### ISSUE THREAD

**Issue by VesaNy** [gtkfi/ArcSDM#88]
Training sites reduction tool seems to require feature layer as a mask (does not allow a grid which is very often used as a mask). Can this be fixed so that it would accept them both?

Executing: SiteReductionTool Orogenic_Au # # true 80 #
Start Time: Wed Apr 25 09:54:10 2018
Running script SiteReductionTool...
Starting sites reduction
------------------------------
Training points:     Orogenic_Au
Scratch workspace:   C:\arcsdm\training\scratch
Using mask:          study_area_g
Mask type:           RasterLayer
Selection layer:     None

Training sites reduction caught arcpy.ExecuteError: 
Reduce training points tool requires mask of type 'FeatureLayer!'
-------------- END EXECUTION ---------------

Traceback (most recent call last):
  File "<string>", line 1219, in execute
  File "C:\ArcSDM5\Toolbox\arcsdm\sitereduction.py", line 352, in ReduceSites
    raise arcpy.ExecuteError;
ExecuteError

Failed to execute (SiteReductionTool).
Failed at Wed Apr 25 09:54:10 2018 (Elapsed Time: 0,16 seconds)

**Comment by tachyon-work** [comment]
Will look at this tonight. Suspect it is the same issue I found when we had this issue with the wofe scripts. Should be simple -
I hope!

**Comment by Eliasmgprado** [comment]
Tried to run this tool on ArcGis Pro 2.1.3, but no tools parameters appears. Same occuring in others tools inside Weights of Evidence.

**Comment by trotor** [comment]
Could you open new issue for this, i will check asap.

**Comment by trotor** [comment]
Works fine on my fresh installation so I assume you have faulty installation of ArcGis pro:
![image](https://user-images.githubusercontent.com/10844537/41894094-890680a2-7926-11e8-8487-85d820df5d73.png)

![image](https://user-images.githubusercontent.com/10844537/41894105-92168e44-7926-11e8-87ba-53a125a40871.png)

**Comment by Eliasmgprado** [comment]
i have open a new issue. I will reinstall mu arcgis and try again, Thnks

**Comment by trotor** [comment]
#100 Issue kind of related. No explanation for the happening

**Comment by trotor** [comment]
Expected to be fixed or worked.
