### ISSUE TITLE
Is there need for tools to inform or stop when ran on ArcGis pro or with mixed environments ?

### ISSUE THREAD

**Issue by trotor** [gtkfi/ArcSDM#91]
Not all tools currently work with arcgis pro - is there need for tools to stop running if ran on wrong environment? Same goes with mixed type inputs like files and filegeodatabase tables.

**Comment by artolaiho** [comment]
ArcSDM Toolbox is now working at least ArcGIS Desktop 10.6.1, ArcGIS Pro 2.5 and ArcGIS Pro 2.6. The toolbox no longer has any ArcGIS Pro restrictions. If the problem persists, reopen this issue.
