### ISSUE TITLE
Experimental tools won't load

### ISSUE THREAD

**Issue by tachyon-work** [gtkfi/ArcSDM#93]
![image](https://user-images.githubusercontent.com/32659237/39562396-278a7186-4eb4-11e8-89b0-e8f8bf6e924e.png)

Toolbox is crossed out. Is this intentional in this release?

**Comment by floodi** [comment]
I think scikit-learn library is not installed. Installation instructions are here:
https://github.com/gtkfi/ArcSDM/wiki/Howto-start.

**Comment by tachyon-work** [comment]
Yup. Got it. Thanks :)

**Comment by floodi** [comment]
Toolbox loading errors can be inspected by right-clicking the toolbox in ArcCatalog and choosing 'Check Syntax'-option. 
![check_syntax](https://user-images.githubusercontent.com/19922263/39562838-686fec6a-4eb6-11e8-8266-cbcad7e373d4.png)
