### ISSUE TITLE
LR fails

### ISSUE THREAD

**Issue by tachyon-work** [gtkfi/ArcSDM#94]
![1525342072227-536265399](https://user-images.githubusercontent.com/32659237/39571060-f5e5a9e2-4ed2-11e8-8b57-81ba1fd55192.jpg)

**Comment by tachyon-work** [comment]
I added you on skype for business. 

Started a new totally empty workspace and added everything in from scratch, and redid all the environment settings from scratch. Same problem.

**Comment by tachyon-work** [comment]
So, interesting result here...

I just ran LR on one of my own project datasets and it worked without issue. Not sure what's going on with the demo data?

**Comment by trotor** [comment]
Did you sort this out by yourself? I can't reproduce this here...

**Comment by tachyon-work** [comment]
It’s an issue with the mask in the demo dataset, not with ArcSDM itself. The mask has to be a single value integer raster, it doesn’t work if the integer raster has multiple classes. 

Resolved, but worth noting this in the documentation.
