### ISSUE TITLE
ArcSDM toolbox - some tools fail to load

### ISSUE THREAD

**Issue by trotor** [gtkfi/ArcSDM#96]
![image](https://user-images.githubusercontent.com/10844537/40040900-c367bd38-5824-11e8-882a-3659a8185dc1.png)

**Comment by trotor** [comment]
This seems like either .pyt file is corrupt or some new issue with arcgis desktop 10.6 - can anyone verify this? 

TODO: Need to install 10.6 on some test machine.

**Comment by tachyon-work** [comment]
It is loading on every other version of ArcGIS desktop we have in the office (10.3, 10.4, and 10.5), so I don't think the .pyt file is corrupt.

**Comment by trotor** [comment]
Okay, waiting for virtual desktop installation of 10.6 to complete.

**Comment by trotor** [comment]
![image](https://user-images.githubusercontent.com/10844537/40112184-dcc584f6-590d-11e8-9dc0-38c90645132b.png)

Can't confirm any error on fresh installation of Arcgis desktop 10.6 - is there something else diffrently than with default installation?

**Comment by trotor** [comment]
Hi and thank you for your message - what does it say when you browse to
arcsdm directory, right click toolbox file and select "Check syntax" on
catalog window inside ArcGis desktop?

**Comment by susimachado** [comment]
Ok,

ArcSDM.pyt:
![capturar](https://user-images.githubusercontent.com/39741101/40685532-e49e04e8-636a-11e8-9294-875577b89760.JPG)

Experimental_tools.pyt:
![capturar2](https://user-images.githubusercontent.com/39741101/40685565-f9956562-636a-11e8-817e-58b91ba63e2e.JPG)

**Comment by trotor** [comment]
Seems like it is somekind of python or numpy installation problem - do you have multiple setups of python on your computer?  It could also be ArcGis desktop installation problem.... I will try to reproduce this and read more about it. 

The meaningful error here is **ImportError: Cannot import name multiarray.**

**Comment by susimachado** [comment]
What is "numpy"?

**Comment by trotor** [comment]
No there shouldn't be any problem with default installation, that is the
interesting part as it should work. Numpy is "numerical python" additional
library for python for high performance numerical computing. It should be
installed but internet says there are some cross lib problems. Do you have
multiple python installations? Most likely no?

**Comment by susimachado** [comment]
I'm sorry i'm not expert on this. How do i check if i have multiple python installations?

**Comment by trotor** [comment]
I am having similar problems now with 10.6, I think something has changed (perhaps windows update?) on low level and it is causing problems. 

You can see if you have multiple installations by searching through your start menu. i wish there was someone else who could confirm this bug, because we don't currently have 10.6 easily accessible for us.

**Comment by trotor** [comment]
Could you try : "python -m pip install numpy --upgrade" in abovementioned python command prompt?

**Comment by susimachado** [comment]
Ok, that's the response

![image](https://user-images.githubusercontent.com/39741101/40983012-04cf8332-68b5-11e8-8d96-996864ef2129.png)

**Comment by susimachado** [comment]
The problem persists.

**Comment by trotor** [comment]
Ah, I got into something! There seems to be old version of numpy coming with 10.6
C:\tmp>python -c "import numpy;print numpy.__version__;print numpy.__file__";
1.9.3
C:\Python27\ArcGIS10.6\lib\site-packages\numpy\__init__.pyc

Type this to python command prompt and verify the version:
`python -c "import numpy;print numpy.__version__;print numpy.__file__";`

On working 10.4.1 computer it is the latest (or atleast much newer) version which is 1.14.something. 
Scikit-learn doesn't seem to work with that - multiarray fails to load.

**Comment by trotor** [comment]
Reported and asked for help from ESRI

**Comment by susimachado** [comment]
The version in my computer is 1.14.3

![image](https://user-images.githubusercontent.com/39741101/41038478-ab23e392-696c-11e8-89fa-023b3feeab9d.png)

**Comment by trotor** [comment]
Hmm.. weird... judging by this image: https://user-images.githubusercontent.com/39741101/40685565-f9956562-636a-11e8-817e-58b91ba63e2e.JPG  you seem to have alternative python installation on your computer under program files arcgis directory. Python toolbox seems to be calling that.


I would suggest cleanup of Arcgis (all components) and then going through default installation again.

**Comment by rosadav** [comment]
Hi!
I am having the same problem as the first post with arcgis 10.5.1.
Only some tools failed to load.
Have you find a solution?
Thanks!
![40040900-c367bd38-5824-11e8-882a-3659a8185dc1](https://user-images.githubusercontent.com/32359827/70319577-e9483680-1822-11ea-9902-74f08000737c.png)

**Comment by qiao1025566574** [comment]
Same problem

**Comment by qiao1025566574** [comment]
I think I get the point. You must confirm that ArcSDM.pyt is consistent with ArcSDM.*.pyt.xml. 
For example, there is no displayName="Success" in ArcSDM.CalculateWeigtsTool.pyt.xml, but displayName="Success" appears in ArcSDM.pyt. So delete this code, CalculateWeightsTool will work.
`paramSuccess = arcpy.Parameter(
        displayName="Success",
        name="success",
        datatype="Boolean",
        parameterType="Optional",
        direction="Output")` 
As for other tools, just find *.pyt.xml and modify code in ArcSDM.pyt, eveything will be OK!!!(This error took me two days. *-*)
<img width="620" alt="Snipaste_2020-04-27_15-13-46" src="https://user-images.githubusercontent.com/20733440/80344277-e5808380-8899-11ea-808b-6ee2524dd967.png">

**Comment by trotor** [comment]
If I recall right ARcMap creates and updates those XML files automatically. Perhaps there is somekind of permission problem? These sools (except experimental) seem to work and load again on 10.7.1

**Comment by artolaiho** [comment]
Load the newest version of ArcSDM (V5.02) and test again. If the problem persists, reopen this issue.

**Comment by SaniUsman-ai** [comment]
Good morning please yesterday I installed ARCSDM PLUGINS when I trying running the analysis it prompt that I don't have license please is there trial version
